(() => {
'use strict';
const D = window.OQ_DATA;
const PLACES = D.places, CATS = D.cats, ROUTES = D.routes, MISSIONS = D.missions;
const STATE_KEY='oq_v4_state', OLD_VISITS='olomouc_visits_v2', OLD_NICK='olomouc_nickname', DEVICE_KEY='oq_v4_device';
const FIREBASE_CONFIG={apiKey:'AIzaSyCOMtm6UGqMfnqUu8aIdNF3aULcLBlTgBk',authDomain:'olomouc-2026-dca3c.firebaseapp.com',projectId:'olomouc-2026-dca3c',storageBucket:'olomouc-2026-dca3c.firebasestorage.app',messagingSenderId:'87040929426',appId:'1:87040929426:web:0315a17940ac88efaa804b'};
const FAMILY_LABELS={all:'Todo',useful:'Esenciales',food:'Comer',night:'Noche',culture:'Cultura',nature:'Naturaleza',free:'Gratis',unvisited:'Sin guardar'};
const FAMILY_LABELS_EN={all:'All',useful:'Essentials',food:'Food',night:'Nightlife',culture:'Culture',nature:'Outdoors',free:'Free',unvisited:'Not saved'};
const CAT_EN={essential:'Erasmus essentials',canteen:'UP canteens',health:'Health & emergencies',service:'Useful services',bar:'Bars',club:'Clubs',gym:'Gyms',dorm:'Dormitories',faculty:'UP faculties',market:'Supermarkets',restaurant:'Restaurants',cafe:'Cafés',park:'Parks',landmark:'Landmarks',museum:'Museums',church:'Churches',viewpoint:'Viewpoints & mountains',secret:'Hidden spots',activity:'Activities',ski:'Mountains & snow',daytrip:'Day trips',freetour:'Tours & information',town:'Nearby towns'};
const ROUTE_EN={
  'connect-campuses':{name:'Connect Neředín and Envelopa',description:'Learn the route between the two dorm areas and the useful services in between.',difficulty:'Easy',best:'Your first days',transport:'Tram 2/7 + walk'},
  'first-day':{name:'A practical first day',description:'Student card, transport, food and orientation without wasting the day.',difficulty:'Easy',best:'When you arrive',transport:'Tram + walk'},
  'historic-center':{name:'Historic centre essentials',description:'The best first route to understand Olomouc and find its main squares.',difficulty:'Easy',best:'Any afternoon',transport:'On foot'},
  'hidden-olomouc':{name:'Hidden Olomouc',description:'Courtyards, passages and places beyond the usual tourist route.',difficulty:'Easy',best:'Afternoon and evening',transport:'On foot'},
  'svaty-day':{name:'A day in Svatý Kopeček',description:'Views, basilica, zoo and rope park in the same area.',difficulty:'Easy–moderate',best:'A clear day',transport:'Bus 11 / bike'},
  'podebrady-bike':{name:'An afternoon at Poděbrady',description:'An easy nature escape for cycling, swimming and a picnic.',difficulty:'Easy',best:'Warm and sunny',transport:'Bike'},
  'litovel-bike':{name:'Olomouc–Litovel by bike',description:'Riverside forests, villages and the option to return by train.',difficulty:'Moderate',best:'Spring or autumn',transport:'Bike + optional train'},
  'bouzov-caves':{name:'Bouzov and Javoříčko',description:'A fairytale castle and caves on a classic day trip from Olomouc.',difficulty:'Easy',best:'April–October',transport:'Shared car / bus'},
  'hranice':{name:'Hranice: abyss and caves',description:'A geological day trip that is easy to organise without a car.',difficulty:'Easy–moderate',best:'All year',transport:'Train'},
  'praded':{name:'Bílá Opava and Praděd',description:'The big waterfall and mountain route in the Jeseníky range.',difficulty:'Moderate–hard',best:'June–October',transport:'Car / coordinated bus'},
  'ramzova':{name:'Ramzová–Šerák–Keprník',description:'A mountain ridge accessible by train, with a chairlift option.',difficulty:'Moderate–hard',best:'May–October',transport:'Train'},
  'winter':{name:'Winter in Kouty',description:'Skiing or a winter mountain day with a station beside the resort.',difficulty:'Variable',best:'With snow',transport:'Train'}
};
const RESIDENCE_GUIDES={
  neredin:{title:{es:'Neředín: lo esencial a mano',en:'Neředín: essentials close by'},facts:{es:['Menza universitaria dentro del campus','Lavandería y secado en Neředín II','Tranvías 2 y 7 y bus 26 en Neředín–krematorium','Deporte, Facultad de Cultura Física y BALUO junto a las residencias'],en:['University canteen on campus','Laundry and drying room in Neředín II','Trams 2 and 7 and bus 26 at Neředín–krematorium','Sports, the Faculty of Physical Culture and BALUO beside the dorms']},source:'https://skm.upol.cz/en/accommodation/neredin-campus/',places:['Campus Neředín (residencias Erasmus)','Menza Neředín','Parada Neředín, krematorium','Facultad de Cultura Física y Deporte','Globus Olomouc','Kaufland Olomouc-Neředín']},
  envelopa:{title:{es:'Envelopa: campus y centro al lado',en:'Envelopa: campus and city centre together'},facts:{es:['Dos menzas y FreshUP+ en el campus','Lavandería, salas de estudio y cocinas en las residencias','Facultades de Ciencias, Derecho, Educación y Artes muy cerca','Centro y estación principal accesibles a pie o en pocos minutos'],en:['Two canteens and FreshUP+ on campus','Laundry, study rooms and kitchens in the dorms','Science, Law, Education and Arts faculties nearby','City centre and main station within walking distance or a short ride']},source:'https://skm.upol.cz/en/accommodation/envelopa-campus/',places:['Campus Envelopa (residencias Erasmus)','Oficina de alojamiento internacional UP','FreshUP+ – cena y comida de tarde','Menza 17. listopadu','Facultad de Artes (Filosofía y Letras)','Parada Envelopa','Albert Šantovka']}
};
const ARRIVAL_TASKS=[
  {id:'welcome',icon:'01',es:['Localiza la Welcome Office','Tu primer punto de ayuda en la universidad.'],en:['Find the Welcome Office','Your first point of support at the university.']},
  {id:'isic',icon:'02',es:['Recoge tu tarjeta UP / ISIC','La necesitarás para biblioteca, comedor y descuentos.'],en:['Pick up your UP / ISIC card','You will need it for the library, canteen and discounts.']},
  {id:'transport',icon:'03',es:['Prepara tu abono de transporte','Guarda cómo llegar desde tu residencia.'],en:['Set up your transport pass','Save the route from your dorm.']},
  {id:'faculty',icon:'04',es:['Comprueba la ruta a tu facultad','Haz el trayecto antes de tu primer día.'],en:['Check the route to your faculty','Try the journey before your first day.']},
  {id:'basics',icon:'05',es:['Ubica supermercado y lavandería','Dos sitios que agradecerás tener guardados.'],en:['Find a supermarket and laundry','Two places worth saving right away.']},
  {id:'people',icon:'06',es:['Conecta con ESN o crea tu grupo','Ten un espacio común para compartir planes.'],en:['Connect with ESN or create a group','Keep a shared space for your plans.']}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const byId=id=>document.getElementById(id);
const placeById=id=>PLACES.find(p=>p.id===id);
const placeByName=name=>PLACES.find(p=>p.name===name);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=(iso,opts={day:'numeric',month:'short'})=>new Intl.DateTimeFormat(state?.language==='en'?'en-GB':'es-ES',opts).format(new Date(iso));
const fmtDateTime=iso=>new Intl.DateTimeFormat(state?.language==='en'?'en-GB':'es-ES',{dateStyle:'medium',timeStyle:'short'}).format(new Date(iso));
const uid=()=>crypto.randomUUID?crypto.randomUUID():'id-'+Date.now()+'-'+Math.random().toString(36).slice(2);
function getDeviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=uid();localStorage.setItem(DEVICE_KEY,id)}return id}
function defaultState(){return{nickname:'',visited:{},groupCode:'',personalEvents:[],localGroup:null,votes:{},comments:{},statusReports:{},mapScope:'city',mapFilter:'all',agendaFilter:'all',language:'es',profile:{residence:'',faculty:'',priority:'useful'},arrivalTasks:{}}}
function loadState(){
  let s=defaultState();
  try{const raw=localStorage.getItem(STATE_KEY);if(raw)s={...s,...JSON.parse(raw)};
    if(!Object.keys(s.visited||{}).length){const old=JSON.parse(localStorage.getItem(OLD_VISITS)||'{}');s.visited=old||{}}
    if(!s.nickname)s.nickname=localStorage.getItem(OLD_NICK)||'';
    s.profile={...defaultState().profile,...(s.profile||{})};s.arrivalTasks=s.arrivalTasks||{};
    if(s.profile.faculty==='Facultad de Filosofía y Letras')s.profile.faculty='Facultad de Artes (Filosofía y Letras)';
  }catch(e){console.warn(e)}
  return s;
}
let state=loadState();
const t=(es,en)=>state.language==='en'?en:es;
const routeCopy=r=>state.language==='en'?{...r,...(ROUTE_EN[r.id]||{})}:r;
const catLabel=cat=>state.language==='en'?(CAT_EN[cat]||CATS[cat].label):CATS[cat].label;
const STATIC_COPY=[
  ['.brand small','Tu guía Erasmus','Your Erasmus guide'],['.hero .eyebrow','Todo lo importante · en un solo lugar','Everything important · in one place'],['#homeTitle','Empieza bien tu Erasmus en Olomouc','Start your Erasmus in Olomouc with confidence'],['.hero p','Resuelve tus primeros días, encuentra lo que necesitas y convierte cualquier descubrimiento en un plan con tu gente.','Settle in, find what you need and turn every discovery into a plan with your people.'],
  ['.hero [data-action="edit-setup"]','Personalizar mi guía','Personalise my guide'],['.hero [data-view="map"]','Explorar cerca','Explore nearby'],['.level-card .section-kicker','Tu base en Olomouc','Your base in Olomouc'],['.level-card > .text-button','Editar','Edit'],['.arrival-card .section-kicker','Primeras 72 horas','First 72 hours'],['#arrivalTitle','Tu llegada, paso a paso','Your arrival, step by step'],['[data-action="show-arrival"] strong','Primeros días','First days'],['[data-action="show-arrival"] small','Tu checklist de llegada','Your arrival checklist'],['#nearMeHome strong','Cerca de mí','Near me'],['#nearMeHome small','Lugares por distancia','Places by distance'],['#transportHome strong','Cómo llegar','Getting around'],['#transportHome small','Residencias y facultades','Dorms and faculties'],['#groupsHome strong','Mi grupo','My group'],['#groupsHome small','Comparte planes privados','Share private plans'],['.content-section:has(#homeRecommendations) .section-kicker','Para ti','For you'],['.content-section:has(#homeRecommendations) h2','Recomendaciones prácticas','Practical recommendations'],['.content-section:has(#homeRecommendations) [data-view="map"]','Ver mapa','View map'],['#residenceSection .section-kicker','Tu zona','Your area'],['#residenceSection h2','Cerca de tu residencia','Near your dorm'],['#residenceSection [data-action="edit-setup"]','Cambiar base','Change base'],['.content-section:has(#homeEvents) .section-kicker','Próximamente','Coming up'],['.content-section:has(#homeEvents) h2','Tus próximos planes','Your upcoming plans'],['.content-section:has(#homeEvents) [data-view="agenda"]','Ver todo','View all'],['.content-section:has(.route-scroll) .section-kicker','Plan listo','Ready-made plans'],['.content-section:has(.route-scroll) h2','Rutas recomendadas','Recommended routes'],['.content-section:has(.route-scroll) [data-view="routes"]','Ver todas','View all'],
  ['#view-routes .page-intro .eyebrow','Planes listos para compartir','Ready to share'],['#routesTitle','De descubrir una ruta a quedar con tu grupo','From finding a route to meeting your group'],['#view-routes .page-intro p','Elige por tiempo y presupuesto, revisa las paradas y añádela directamente a tus planes.','Choose by time and budget, review the stops and add it directly to your plans.'],['[data-route-filter="all"]','Todas','All'],['[data-route-filter="urban"]','Ciudad','City'],['[data-route-filter="nature"]','Naturaleza','Nature'],['[data-route-filter="trip"]','Escapadas','Day trips'],['[data-route-filter="mountain"]','Montaña','Mountains'],
  ['#view-agenda .page-intro .eyebrow','Todo lo que vas a hacer','Everything you are going to do'],['#agendaTitle','Planes oficiales, personales y de grupo','Official, personal and group plans'],['#view-agenda .page-intro p','Crea una quedada, guarda una ruta o comparte los próximos eventos sin perderlos entre mensajes.','Create a meetup, save a route or share upcoming events without losing them in messages.'],['#addEventBtn','＋ Añadir plan','＋ Add plan'],['#shareAgendaBtn','Compartir próximos','Share upcoming'],['[data-agenda-filter="all"]','Todo','All'],['[data-agenda-filter="official"]','Oficial','Official'],['[data-agenda-filter="group"]','Grupo','Group'],['[data-agenda-filter="personal"]','Personal','Personal'],['#placeSearch','Buscar sitio, categoría o etiqueta','Search place, category or tag'],['#view-profile .profile-header .eyebrow','Pasaporte Erasmus','Erasmus passport'],['#editNameBtn','Editar','Edit'],['#profilePoints + span','Lugares','Places'],['#profileVisits + span','Planes','Plans'],['#profileVerified + span','Verificadas','Verified'],['#profilePhotos + span','Fotos','Photos'],['.content-section:has(#groupPanel) .section-kicker','Comunidad','Community'],['.content-section:has(#groupPanel) h2','Grupos','Groups'],['#groupManageBtn','Gestionar','Manage'],['.content-section:has(#missionsList) .section-kicker','Tu historia','Your story'],['.content-section:has(#missionsList) h2','Colecciones','Collections'],['.content-section:has(#photoGallery) .section-kicker','Recuerdos','Memories'],['.content-section:has(#photoGallery) h2','Fotos de visitas','Visit photos'],['#transportProfile span','🚋 Transporte y facultades','🚋 Transport and faculties'],['#offlineProfile span','⇩ Modo sin conexión','⇩ Offline mode'],['#emergencyProfile span','🆘 Emergencias','🆘 Emergencies'],['#resetBtn span','Reiniciar progreso local','Reset local progress'],
  ['[data-view="home"] small','Inicio','Home'],['[data-view="map"] small','Mapa','Map'],['[data-view="routes"] small','Rutas','Routes'],['[data-view="agenda"] small','Planes','Plans'],['[data-view="profile"] small','Pasaporte','Passport']
];
function applyLanguage(){document.documentElement.lang=state.language;byId('langBtn').textContent=state.language==='en'?'ES':'EN';byId('langBtn').title=t('Cambiar a inglés','Switch to Spanish');byId('langBtn').setAttribute('aria-label',t('Cambiar a inglés','Switch to Spanish'));STATIC_COPY.forEach(([sel,es,en])=>document.querySelectorAll(sel).forEach(el=>el instanceof HTMLInputElement?el.placeholder=t(es,en):el.textContent=t(es,en)));document.title=t('Olomouc Quest · Tu Erasmus en Olomouc','Olomouc Quest · Your Erasmus in Olomouc');document.querySelector('meta[name="description"]').content=t('Olomouc Quest: tu guía práctica para instalarte, moverte y hacer planes durante tu Erasmus en Olomouc.','Olomouc Quest: your practical guide to settling in, getting around and making plans during your Erasmus in Olomouc.');updateNetwork()}
function saveState(){localStorage.setItem(STATE_KEY,JSON.stringify(state))}
function toast(msg){const el=byId('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3200)}
function haversine(a,b){const R=6371000,r=x=>x*Math.PI/180,dLat=r(b.lat-a.lat),dLng=r(b.lng-a.lng);const q=Math.sin(dLat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function visitedEntry(p){return state.visited[p.id]}
function isVisited(p){return !!visitedEntry(p)}
function isVerified(p){return !!visitedEntry(p)?.verified}
function missionPlaces(m){return PLACES.filter(p=>(m.placeNames&&m.placeNames.includes(p.name))||(m.categories&&m.categories.includes(p.cat))||(m.scopes&&m.scopes.includes(p.scope)))}
function missionProgress(m){const all=missionPlaces(m),done=all.filter(isVisited),target=Math.min(m.target||all.length,all.length);return{done:Math.min(done.length,target),target,complete:done.length>=target,pct:target?Math.round(Math.min(done.length,target)/target*100):0}}

let db=null,firebaseReady=false;
try{if(window.firebase){firebase.initializeApp(FIREBASE_CONFIG);db=firebase.firestore();firebaseReady=true}}catch(e){console.warn('Firebase:',e)}
async function syncPlayer(){
  if(!firebaseReady||!state.nickname)return;
  const data={name:state.nickname,visitedCount:PLACES.filter(isVisited).length,verifiedCount:PLACES.filter(p=>isVerified(p)).length,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};
  try{
    if(state.groupCode)await db.collection('groups').doc(state.groupCode).collection('members').doc(getDeviceId()).set(data,{merge:true});
  }catch(e){console.warn('Sync failed',e)}
}

function setView(name){
  $$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));
  $$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));
  window.scrollTo({top:0,behavior:'instant'});
  if(name==='map'){initMap();setTimeout(()=>map?.invalidateSize(),120)}
  if(name==='profile')renderProfile();
  if(name==='agenda')renderAgenda();
  if(name==='routes')renderRoutes();
}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));

function updateNetwork(){const on=navigator.onLine,el=byId('networkBadge');el.textContent=on?t('En línea','Online'):t('Sin conexión','Offline');el.classList.toggle('offline',!on);el.classList.toggle('online',on)}
window.addEventListener('online',()=>{updateNetwork();toast(t('Conexión recuperada','Connection restored'));syncPlayer()});window.addEventListener('offline',()=>{updateNetwork();toast(t('Modo sin conexión activo','Offline mode active'))});updateNetwork();
byId('langBtn').addEventListener('click',()=>{state.language=state.language==='en'?'es':'en';saveState();applyLanguage();renderRoutes();renderHome();renderAgenda();renderProfile();if(map){renderMapFilters();renderMapMarkers()}toast(t('Idioma cambiado a español.','Language changed to English.'))});
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;byId('installBtn').classList.remove('hidden')});
byId('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return openOffline();deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;byId('installBtn').classList.add('hidden')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));

function setupLabels(){const residence={neredin:'Neředín',envelopa:'Envelopa',other:t('Otra residencia','Other accommodation')}[state.profile.residence]||'';let faculty=D.facultyTravel.find(x=>x.placeName===state.profile.faculty)?.name||'';if(state.language==='en')faculty=faculty.replace('Facultad de Artes (Filosofía y Letras)','Faculty of Arts').replace('Facultad de','Faculty of').replace('Entre Neředín y Envelopa','Between Neředín and Envelopa');return{residence,faculty}}
function renderSetup(){const labels=setupLabels(),ready=labels.residence||labels.faculty;byId('setupIcon').textContent=state.profile.residence==='envelopa'?'E':state.profile.residence==='neredin'?'N':'⌂';byId('setupTitle').textContent=ready?[labels.residence,labels.faculty].filter(Boolean).join(' · '):t('Configura residencia y facultad','Set your dorm and faculty');byId('setupSummary').textContent=ready?t('Tus recomendaciones ya están personalizadas.','Your recommendations are personalised.'):t('Te mostraremos información relevante para ti.','We will show the information that matters to you.')}
function openSetup(){const facultyOptions=D.facultyTravel.map(x=>`<option value="${esc(x.placeName)}" ${state.profile.faculty===x.placeName?'selected':''}>${esc(state.language==='en'?setupFacultyName(x.name):x.name)}</option>`).join('');openModal(`<span class="eyebrow" style="color:var(--terracotta)">${t('Tu guía personal','Your personal guide')}</span><h2>${t('¿Cuál será tu base?','Where will you be based?')}</h2><p>${t('Usamos estos datos solo en este dispositivo para ordenar la información más útil para ti.','These preferences stay on this device and help us prioritise useful information.')}</p><div class="form-grid"><label class="field-label">${t('Residencia','Accommodation')}<select id="setupResidence"><option value="">${t('Selecciona una opción','Select an option')}</option><option value="neredin" ${state.profile.residence==='neredin'?'selected':''}>Neředín</option><option value="envelopa" ${state.profile.residence==='envelopa'?'selected':''}>Envelopa</option><option value="other" ${state.profile.residence==='other'?'selected':''}>${t('Otra residencia','Other accommodation')}</option></select></label><label class="field-label">${t('Facultad','Faculty')}<select id="setupFaculty"><option value="">${t('Selecciona tu facultad','Select your faculty')}</option>${facultyOptions}</select></label><label class="field-label">${t('Qué quieres encontrar primero','What do you want to find first')}<select id="setupPriority"><option value="useful" ${state.profile.priority==='useful'?'selected':''}>${t('Servicios y trámites','Services and admin')}</option><option value="food" ${state.profile.priority==='food'?'selected':''}>${t('Comer bien y barato','Affordable food')}</option><option value="nature" ${state.profile.priority==='nature'?'selected':''}>${t('Naturaleza y deporte','Nature and sport')}</option><option value="culture" ${state.profile.priority==='culture'?'selected':''}>${t('Cultura y ciudad','Culture and city')}</option><option value="night" ${state.profile.priority==='night'?'selected':''}>${t('Vida nocturna','Nightlife')}</option></select></label><button class="primary-button" data-action="save-setup">${t('Guardar preferencias','Save preferences')}</button></div>`)}
function setupFacultyName(name){return name.replace('Entre Neředín y Envelopa','Between Neředín and Envelopa').replace('Facultad de Artes (Filosofía y Letras)','Faculty of Arts').replace('Facultad de Cultura Física y Deporte','Faculty of Physical Culture').replace('Facultad de Ciencias de la Salud','Faculty of Health Sciences').replace('Facultad de Ciencias','Faculty of Science').replace('Facultad de Derecho','Faculty of Law').replace('Facultad de Educación','Faculty of Education').replace('Facultad de Teología','Faculty of Theology').replace('Facultad de Medicina','Faculty of Medicine')}
function saveSetup(){state.profile={residence:byId('setupResidence').value,faculty:byId('setupFaculty').value,priority:byId('setupPriority').value};saveState();closeModal();renderHome();renderProfile();toast(t('Tu guía ya está personalizada.','Your guide is now personalised.'))}
function renderArrival(){const done=ARRIVAL_TASKS.filter(x=>state.arrivalTasks[x.id]).length;byId('arrivalCount').textContent=`${done}/${ARRIVAL_TASKS.length}`;byId('arrivalProgress').style.width=`${Math.round(done/ARRIVAL_TASKS.length*100)}%`;byId('arrivalChecklist').innerHTML=ARRIVAL_TASKS.map(x=>{const copy=x[state.language];return`<button class="arrival-item ${state.arrivalTasks[x.id]?'done':''}" aria-pressed="${!!state.arrivalTasks[x.id]}" data-action="arrival-toggle" data-task-id="${x.id}" type="button"><span class="arrival-number">${state.arrivalTasks[x.id]?'✓':x.icon}</span><span><strong>${esc(copy[0])}</strong><small>${esc(copy[1])}</small></span></button>`}).join('')}
function recommendedPlaces(){const result=[];const add=p=>{if(p&&!result.includes(p))result.push(p)};if(state.profile.residence==='neredin')add(PLACES.find(p=>p.cat==='dorm'&&p.name.toLowerCase().includes('neředín')));if(state.profile.residence==='envelopa')add(PLACES.find(p=>p.cat==='dorm'&&p.name.toLowerCase().includes('envelopa')));add(placeByName(state.profile.faculty));add(PLACES.find(p=>CATS[p.cat].family===state.profile.priority&&p.scope==='city'));add(PLACES.find(p=>p.cat==='essential'));add(PLACES.find(p=>p.cat==='market'));return result.slice(0,3)}
function renderRecommendations(){const list=recommendedPlaces();byId('homeRecommendations').innerHTML=list.map(p=>`<button class="recommendation-row" data-action="place-detail" data-place-id="${p.id}" type="button"><span class="recommendation-icon">${CATS[p.cat].icon}</span><span><strong>${esc(state.language==='en'&&p.name==='Facultad de Artes (Filosofía y Letras)'?'Faculty of Arts':p.name)}</strong><small>${esc(catLabel(p.cat))} · ${esc(p.budgetLabel)}</small></span><b>›</b></button>`).join('')}
function renderResidenceGuide(){const key=state.profile.residence,section=byId('residenceSection'),guide=RESIDENCE_GUIDES[key];section.classList.toggle('needs-setup',!guide);if(!guide){byId('residenceGuide').innerHTML=`<div class="empty-state">${t('Selecciona Neředín o Envelopa para ver servicios y lugares útiles junto a tu residencia.','Select Neředín or Envelopa to see useful services and places near your dorm.')}</div>`;byId('residencePlaces').innerHTML='';return}const facts=guide.facts[state.language];byId('residenceGuide').innerHTML=`<div><span class="verified-label">✓ ${t('Comprobado con información de UPOL','Checked against UPOL information')}</span><h3>${esc(guide.title[state.language])}</h3><ul>${facts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><button class="text-button" data-action="external" data-url="${guide.source}">${t('Ver fuente oficial →','Official source →')}</button></div>`;byId('residencePlaces').innerHTML=guide.places.map(placeByName).filter(Boolean).map(p=>`<button class="recommendation-row" data-action="place-detail" data-place-id="${p.id}" type="button"><span class="recommendation-icon">${CATS[p.cat].icon}</span><span><strong>${esc(state.language==='en'&&p.name==='Facultad de Artes (Filosofía y Letras)'?'Faculty of Arts':p.name)}</strong><small>${esc(catLabel(p.cat))} · ${esc(p.budgetLabel)}</small></span><b>›</b></button>`).join('')}
function renderHome(){renderSetup();renderArrival();renderRecommendations();renderResidenceGuide();const upcoming=combinedEvents().filter(e=>new Date(e.end||e.start)>=new Date()).sort((a,b)=>new Date(a.start)-new Date(b.start)).slice(0,3);byId('homeEvents').innerHTML=upcoming.length?upcoming.map(eventMiniHtml).join(''):`<div class="empty-state"><span>□</span>${t('No hay próximos planes.','No upcoming plans.')}</div>`;byId('homeRoutes').innerHTML=ROUTES.slice(0,5).map(routePreviewHtml).join('')}
function eventMiniHtml(e){const d=new Date(e.start);return`<article class="event-mini"><div class="date-box"><strong>${d.getDate()}</strong><small>${fmtDate(e.start,{month:'short'})}</small></div><div><h3>${esc(e.title)}</h3><p>${esc(e.location||t('Sin ubicación','No location'))} · ${e.type==='official'?t('Oficial','Official'):e.type==='group'?t('Grupo','Group'):t('Personal','Personal')}</p></div><button data-action="event-detail" data-event-id="${esc(e.id)}">›</button></article>`}
function routePreviewHtml(original){const r=routeCopy(original);return`<article class="route-preview"><div class="route-icon">${r.icon}</div><h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><div class="meta-line"><span class="meta-pill">${esc(r.duration)}</span><span class="meta-pill">${esc(r.budget)}</span></div><button class="text-button" data-action="route-detail" data-route-id="${r.id}">${t('Abrir ruta →','Open route →')}</button></article>`}

let map=null,markersLayer=null,userMarker=null,markerMap=new Map(),lastLocation=null;
function initMap(){
  if(map)return;
  map=L.map('map',{center:[49.594,17.252],zoom:13,zoomControl:false});
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
  L.control.zoom({position:'bottomright'}).addTo(map);
  markersLayer=window.L.markerClusterGroup?L.markerClusterGroup({showCoverageOnHover:false,maxClusterRadius:45}):L.layerGroup();markersLayer.addTo(map);
  renderMapFilters();renderMapMarkers();
}
function markerIcon(p){const c=CATS[p.cat];return L.divIcon({className:'',html:`<div class="custom-pin ${isVisited(p)?'visited':''}" style="background:${c.color}"><span>${c.icon}</span></div>`,iconSize:[35,35],iconAnchor:[17,34]})}
function mapFilteredPlaces(){const q=(byId('placeSearch')?.value||'').trim().toLowerCase(),scope=state.mapScope,filter=state.mapFilter;let list=PLACES.filter(p=>p.scope===scope);if(q)list=list.filter(p=>[p.name,p.addr,p.note,CATS[p.cat].label,...(p.tags||[])].join(' ').toLowerCase().includes(q));if(filter==='free')list=list.filter(p=>p.budgetMin===0);else if(filter==='unvisited')list=list.filter(p=>!isVisited(p));else if(filter!=='all')list=list.filter(p=>CATS[p.cat].family===filter);if(lastLocation)list.sort((a,b)=>haversine(lastLocation,a)-haversine(lastLocation,b));return list}
function renderMapFilters(){const available=['all','useful','food','night','culture','nature','free','unvisited'],labels=state.language==='en'?FAMILY_LABELS_EN:FAMILY_LABELS;byId('mapFilters').innerHTML=available.map(f=>`<button class="filter-chip ${state.mapFilter===f?'active':''}" data-map-filter="${f}">${labels[f]}</button>`).join('')}
function renderMapMarkers(){if(!map)return;markersLayer.clearLayers();markerMap.clear();const list=mapFilteredPlaces();list.forEach(p=>{const m=L.marker([p.lat,p.lng],{icon:markerIcon(p),title:p.name});m.on('click',()=>openPlace(p));markersLayer.addLayer(m);markerMap.set(p.id,m)});byId('mapCount').textContent=list.length;if(list.length&&state.mapScope==='trip'&&!lastLocation){const g=L.featureGroup(list.map(p=>L.marker([p.lat,p.lng])));map.fitBounds(g.getBounds(),{padding:[35,35],maxZoom:9})}}
byId('placeSearch').addEventListener('input',renderMapMarkers);byId('mapFilters').addEventListener('click',e=>{const b=e.target.closest('[data-map-filter]');if(!b)return;state.mapFilter=b.dataset.mapFilter;saveState();renderMapFilters();renderMapMarkers()});
$$('.scope-tab').forEach(b=>b.addEventListener('click',()=>{state.mapScope=b.dataset.scope;state.mapFilter='all';saveState();$$('.scope-tab').forEach(x=>x.classList.toggle('active',x===b));renderMapFilters();renderMapMarkers();if(state.mapScope==='city')map.flyTo([49.594,17.252],13)}));
async function locateUser(openList=false){
  if(!navigator.geolocation)return toast('El navegador no permite ubicación.');toast('Buscando tu posición…');
  navigator.geolocation.getCurrentPosition(pos=>{lastLocation={lat:pos.coords.latitude,lng:pos.coords.longitude};initMap();if(userMarker)map.removeLayer(userMarker);userMarker=L.marker([lastLocation.lat,lastLocation.lng],{icon:L.divIcon({className:'',html:'<div class="user-location"></div>',iconSize:[18,18]})}).addTo(map);map.flyTo([lastLocation.lat,lastLocation.lng],14);renderMapMarkers();toast('Lugares ordenados por distancia.');if(openList)openPlaceList()},()=>toast('No se pudo obtener tu ubicación.'),{enableHighAccuracy:true,timeout:12000,maximumAge:20000})
}
byId('nearMeBtn').addEventListener('click',()=>locateUser(false));byId('nearMeHome').addEventListener('click',()=>{setView('map');setTimeout(()=>locateUser(true),150)});byId('openPlaceList').addEventListener('click',openPlaceList);
function openPlaceList(){const list=mapFilteredPlaces();openSheet(`<h2>${state.mapScope==='city'?'Olomouc':t('Escapadas','Trips')}</h2><p>${lastLocation?t('Ordenado por cercanía.','Sorted by distance.'):t('Activa “Cerca de mí” para ordenar por distancia.','Enable “Near me” to sort by distance.')}</p><div class="stack-list">${list.map(p=>`<button class="list-row" data-action="place-detail" data-place-id="${p.id}" style="width:100%;display:grid;grid-template-columns:38px 1fr auto;align-items:center;text-align:left;padding:11px;border:0"><span style="font-size:21px">${CATS[p.cat].icon}</span><span><strong style="display:block">${esc(p.name)}</strong><small style="color:var(--muted)">${lastLocation?formatDistance(haversine(lastLocation,p))+' · ':''}${esc(p.budgetLabel)}</small></span><b>${isVisited(p)?'✓':'›'}</b></button>`).join('')}</div>`)}
function formatDistance(m){return m<1000?`${Math.round(m/10)*10} m`:`${(m/1000).toFixed(1)} km`}

function statusCommunityHtml(stats){if(!stats)return'';const total=stats.open+stats.closed+stats.outdated;if(!total)return'<span>Sin informes recientes</span>';return`<span>${stats.open} abierto · ${stats.closed} cerrado · ${stats.outdated} horario dudoso</span>`}
async function openPlace(p){
  currentPlaceId=p.id;const c=CATS[p.cat],e=visitedEntry(p),dist=lastLocation?formatDistance(haversine(lastLocation,p)):null;
  openSheet(`<div class="place-hero"><span class="place-category" style="background:${c.color}">${c.icon} ${esc(catLabel(p.cat))}</span><h2 class="place-title">${esc(p.name)}</h2><div class="place-address">${esc(p.addr)}</div></div>
  <div class="place-meta-grid"><div class="place-meta"><small>${t('Presupuesto','Budget')}</small><strong>${esc(p.budgetLabel)}</strong></div><div class="place-meta"><small>${t('Distancia','Distance')}</small><strong>${dist||t('Activa Cerca de mí','Enable Near me')}</strong></div><div class="place-meta"><small>${t('Estado','Status')}</small><strong><i class="status-dot ${p.statusType==='always'||p.statusType==='essential'?'good':''}"></i>${esc(p.statusText)}</strong></div><div class="place-meta"><small>${t('Horario','Hours')}</small><strong>${esc(p.hours||t('Consultar','Check'))}</strong></div></div>
  <p>${esc(state.language==='en'?(p.noteEn||`Practical information for ${p.name}. Check the official source and current opening hours before you go.`):p.note)}</p><div class="tag-row">${(p.tags||[]).slice(0,8).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div>
  <div class="sheet-actions"><button class="primary-button" data-action="visit" data-place-id="${p.id}">${e?(e.verified?t('✓ Visita verificada','✓ Verified visit'):t('✓ En tu pasaporte','✓ In your passport')):t('Guardar en mi pasaporte','Save to my passport')}</button><button class="secondary-button" data-action="directions" data-place-id="${p.id}">${t('Cómo llegar','Directions')}</button></div>
  <div class="sheet-actions"><button class="secondary-button" data-action="photo" data-place-id="${p.id}" ${e?'':'disabled'}>📷 ${t('Foto','Photo')}</button><button class="secondary-button" data-action="share-place" data-place-id="${p.id}">${t('Compartir','Share')}</button></div>
  ${p.officialUrl?`<button class="text-button" data-action="official" data-url="${esc(p.officialUrl)}">${t('Información oficial →','Official information →')}</button>`:''}
  <section class="content-section"><div class="section-heading"><div><span class="section-kicker">${t('Votación rápida','Quick vote')}</span><h3>${t('¿Cómo es para Erasmus?','How is it for Erasmus students?')}</h3></div></div><div id="placeVotes" class="vote-row"><button class="vote-button" data-vote="worth">👍 ${t('Merece la pena','Worth it')}</button><button class="vote-button" data-vote="cheap">💸 ${t('Buen precio','Good value')}</button><button class="vote-button" data-vote="group">👥 ${t('Buen grupo','Good for groups')}</button></div><small id="voteStats">${t('Cargando votos…','Loading votes…')}</small></section>
  <section class="content-section"><div class="section-heading"><div><span class="section-kicker">${t('Estado comunitario','Community status')}</span><h3>${t('¿Está correcto?','Is this correct?')}</h3></div></div><div class="vote-row"><button class="vote-button" data-status-report="open">✅ ${t('Abierto','Open')}</button><button class="vote-button" data-status-report="closed">⛔ ${t('Cerrado','Closed')}</button><button class="vote-button" data-status-report="outdated">🕒 ${t('Horario dudoso','Hours may be outdated')}</button></div><small id="statusStats">${t('Cargando informes…','Loading reports…')}</small></section>
  <section class="content-section"><div class="section-heading"><div><span class="section-kicker">${t('Consejos breves','Quick tips')}</span><h3>${t('Comentarios Erasmus','Erasmus comments')}</h3></div></div><div id="placeComments" class="comment-list"><div class="loading-lines">${t('Cargando…','Loading…')}</div></div><div class="form-grid" style="margin-top:10px"><label class="field-label">${t('Añadir consejo','Add a tip')}<textarea id="commentText" maxlength="180" placeholder="${t('Ej.: reserva, lleva efectivo, mejor los jueves…','E.g. book ahead, bring cash, Thursdays are best…')}"></textarea></label><button class="primary-button" data-action="comment" data-place-id="${p.id}">${t('Publicar comentario','Post comment')}</button></div></section>`);
  loadFeedback(p.id);
}
let currentPlaceId=null;
function attemptVisit(p){
  const existing=visitedEntry(p);if(existing){openModal(`<h2>Ya está en tu pasaporte</h2><p>${existing.verified?'Guardamos que estuviste aquí y verificamos la ubicación.':'Lo guardaste manualmente para recordarlo más tarde.'}</p><div class="modal-actions"><button class="secondary-button" data-action="remove-visit" data-place-id="${p.id}">Eliminar</button><button class="primary-button" data-action="photo" data-place-id="${p.id}">Añadir recuerdo</button></div>`);return}
  if(!navigator.geolocation)return offerUnverified(p,'Este dispositivo no permite comprobar la ubicación.');toast('Comprobando ubicación…');navigator.geolocation.getCurrentPosition(pos=>{const d=haversine({lat:pos.coords.latitude,lng:pos.coords.longitude},p),allowed=p.radius+Math.min(pos.coords.accuracy||0,120);if(d<=allowed){state.visited[p.id]={visitedAt:new Date().toISOString(),verified:true,distance:Math.round(d)};saveState();syncPlayer();renderAll();closeSheet();toast('Visita guardada en tu pasaporte.');setTimeout(()=>askPhoto(p),400)}else offerUnverified(p,`Estás a ${formatDistance(d)}. Para verificarla debes estar a unos ${p.radius} m.`)},err=>offerUnverified(p,err.code===1?'Has denegado la ubicación.':'No se obtuvo una ubicación fiable.'),{enableHighAccuracy:true,timeout:12000,maximumAge:10000})
}
function offerUnverified(p,reason){openModal(`<h2>No se pudo verificar</h2><p>${esc(reason)}</p><p>Puedes guardarlo igualmente en tu pasaporte como lugar pendiente o visitado.</p><div class="modal-actions"><button class="secondary-button" data-action="cancel-modal">Cancelar</button><button class="primary-button" data-action="save-unverified" data-place-id="${p.id}">Guardar igualmente</button></div>`)}
function askPhoto(p){openModal(`<h2>¿Guardar un recuerdo?</h2><p>Añade una foto de la visita. Se comprime y se guarda en este dispositivo para que la app siga siendo rápida.</p><div class="modal-actions"><button class="secondary-button" data-action="cancel-modal">Ahora no</button><button class="primary-button" data-action="photo" data-place-id="${p.id}">Hacer foto</button></div>`)}

// IndexedDB photos
let photoDBPromise=null;function photoDB(){if(photoDBPromise)return photoDBPromise;photoDBPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('oq-v4-photos',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return photoDBPromise}
async function storePhoto(rec){const dbi=await photoDB();return new Promise((res,rej)=>{const tx=dbi.transaction('photos','readwrite');tx.objectStore('photos').put(rec);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function allPhotos(){try{const dbi=await photoDB();return await new Promise((res,rej)=>{const r=dbi.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}catch{return[]}}
let photoTarget=null;byId('photoInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f||!photoTarget)return;toast('Procesando foto…');const data=await compressImage(f);await storePhoto({id:uid(),placeId:photoTarget,createdAt:new Date().toISOString(),data});e.target.value='';photoTarget=null;closeModal();toast('Foto guardada.');renderProfile()});
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.76))};img.onerror=reject;img.src=url})}

async function loadFeedback(placeId){
  const localV=state.votes[placeId]||{},localStatus=state.statusReports[placeId]||'';$$('[data-vote]').forEach(b=>b.classList.toggle('active',!!localV[b.dataset.vote]));$$('[data-status-report]').forEach(b=>b.classList.toggle('active',localStatus===b.dataset.statusReport));
  let comments=(state.comments[placeId]||[]).slice(-8),voteStats={worth:0,cheap:0,group:0},statusStats={open:0,closed:0,outdated:0};
  if(firebaseReady&&navigator.onLine){try{const root=db.collection('place_feedback').doc(placeId);const [cs,vs]=await Promise.all([root.collection('comments').orderBy('createdAt','desc').limit(20).get(),root.collection('votes').limit(250).get()]);comments=cs.docs.map(d=>d.data());vs.docs.forEach(d=>{const x=d.data();['worth','cheap','group'].forEach(k=>{if(x[k])voteStats[k]++});if(statusStats[x.status]!==undefined)statusStats[x.status]++})}catch(e){console.warn(e)}}
  const c=byId('placeComments');if(c)c.innerHTML=comments.length?comments.map(x=>`<div class="comment"><strong>${esc(x.name||'Erasmus')}</strong>${esc(x.text)}</div>`).join(''):'<div class="empty-state">Todavía no hay consejos.</div>';
  const v=byId('voteStats');if(v)v.textContent=`${voteStats.worth} lo recomiendan · ${voteStats.cheap} buen precio · ${voteStats.group} ideal para grupo`;
  const s=byId('statusStats');if(s)s.innerHTML=statusCommunityHtml(statusStats);
}
async function toggleVote(placeId,key){state.votes[placeId]=state.votes[placeId]||{};state.votes[placeId][key]=!state.votes[placeId][key];saveState();if(firebaseReady){try{await db.collection('place_feedback').doc(placeId).collection('votes').doc(getDeviceId()).set({...state.votes[placeId],status:state.statusReports[placeId]||null,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}catch(e){console.warn(e)}}loadFeedback(placeId)}
async function setStatusReport(placeId,status){state.statusReports[placeId]=status;saveState();if(firebaseReady){try{await db.collection('place_feedback').doc(placeId).collection('votes').doc(getDeviceId()).set({...state.votes[placeId],status,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}catch(e){console.warn(e)}}loadFeedback(placeId);toast('Estado registrado.')}
async function addComment(placeId){const input=byId('commentText'),text=input?.value.trim();if(!text)return toast('Escribe un comentario.');const rec={id:uid(),name:state.nickname||'Erasmus',text,createdAt:new Date().toISOString()};state.comments[placeId]=[...(state.comments[placeId]||[]),rec].slice(-30);saveState();input.value='';if(firebaseReady){try{await db.collection('place_feedback').doc(placeId).collection('comments').doc(rec.id).set({...rec,createdAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.warn(e)}}loadFeedback(placeId);toast('Comentario publicado.')}

function renderRoutes(filter='all'){const list=filter==='all'?ROUTES:ROUTES.filter(r=>r.type===filter);byId('routesList').innerHTML=list.map(original=>{const r=routeCopy(original);return`<article class="route-card"><div class="route-card-head"><div><span class="eyebrow" style="color:var(--terracotta)">${esc(r.type)}</span><h2>${r.icon} ${esc(r.name)}</h2></div><span class="meta-pill">${esc(r.difficulty)}</span></div><p>${esc(r.description)}</p><div class="meta-line"><span class="meta-pill">⏱ ${esc(r.duration)}</span><span class="meta-pill">💰 ${esc(r.budget)}</span><span class="meta-pill">🚋 ${esc(r.transport)}</span></div><div class="route-stops">${r.placeNames.slice(0,5).map((n,i)=>`${i?'<i></i>':''}<span>${CATS[placeByName(n)?.cat]?.icon||'•'}</span>`).join('')}</div><div class="route-actions"><button class="primary-button" data-action="route-detail" data-route-id="${r.id}">${t('Ver ruta','View route')}</button><button class="secondary-button" data-action="share-route" data-route-id="${r.id}">${t('Compartir','Share')}</button></div></article>`}).join('')}
byId('routeFilters').addEventListener('click',e=>{const b=e.target.closest('[data-route-filter]');if(!b)return;$$('#routeFilters button').forEach(x=>x.classList.toggle('active',x===b));renderRoutes(b.dataset.routeFilter)});
function openRoute(original){const r=routeCopy(original),stops=r.placeNames.map(n=>placeByName(n)).filter(Boolean);openSheet(`<span class="place-category" style="background:var(--terracotta)">${r.icon} ${t('Ruta preparada','Ready-made route')}</span><h2>${esc(r.name)}</h2><p>${esc(r.description)}</p><div class="place-meta-grid"><div class="place-meta"><small>${t('Duración','Duration')}</small><strong>${esc(r.duration)}</strong></div><div class="place-meta"><small>${t('Presupuesto','Budget')}</small><strong>${esc(r.budget)}</strong></div><div class="place-meta"><small>${t('Dificultad','Difficulty')}</small><strong>${esc(r.difficulty)}</strong></div><div class="place-meta"><small>${t('Mejor momento','Best time')}</small><strong>${esc(r.best)}</strong></div></div><h3>${t('Paradas','Stops')}</h3><div class="stack-list">${stops.map((p,i)=>`<button class="list-row" data-action="place-detail" data-place-id="${p.id}" style="border:0;padding:11px;text-align:left"><strong>${i+1}. ${esc(p.name)}</strong><small style="display:block;color:var(--muted)">${esc(p.addr)}</small></button>`).join('')}</div><div class="sheet-actions"><button class="primary-button" data-action="show-route-map" data-route-id="${r.id}">${t('Ver en mapa','View on map')}</button><button class="secondary-button" data-action="share-route" data-route-id="${r.id}">${t('Compartir','Share')}</button></div><button class="secondary-button" style="width:100%;margin-top:9px" data-action="route-to-agenda" data-route-id="${r.id}">${t('Añadir como plan','Add as a plan')}</button>`)}
function showRouteMap(r){state.mapScope=r.type==='urban'||r.type==='nature'?'city':'trip';saveState();setView('map');setTimeout(()=>{initMap();renderMapMarkers();const ps=r.placeNames.map(placeByName).filter(Boolean);if(ps.length){const g=L.featureGroup(ps.map(p=>L.marker([p.lat,p.lng])));map.fitBounds(g.getBounds(),{padding:[55,55],maxZoom:13})}},150);closeSheet()}
function shareText(title,text,url=''){if(navigator.share)return navigator.share({title,text,url}).catch(()=>{});navigator.clipboard?.writeText(`${title}\n${text}\n${url}`).then(()=>toast('Copiado para compartir.')).catch(()=>toast('No se pudo compartir.'))}
function shareRoute(r){shareText(`Plan Erasmus: ${r.name}`,`${r.icon} ${r.name}\n${r.duration} · ${r.budget} · ${r.transport}\n${r.description}\nParadas: ${r.placeNames.join(' → ')}`,location.href)}

function combinedEvents(){const group=groupPlansCache.map(x=>({...x,type:'group'}));return[...D.events,...state.personalEvents,...group]}
function renderAgenda(){const f=state.agendaFilter||'all',events=combinedEvents().filter(e=>f==='all'||e.type===f).sort((a,b)=>new Date(a.start)-new Date(b.start));byId('agendaList').innerHTML=events.length?events.map(e=>{const past=new Date(e.end||e.start)<new Date();return`<article class="agenda-card ${past?'past':''}"><div class="date-box"><strong>${new Date(e.start).getDate()}</strong><small>${fmtDate(e.start,{month:'short'})}</small></div><div><span class="eyebrow" style="color:var(--terracotta)">${e.type==='official'?t('Oficial','Official'):e.type==='group'?t('Grupo','Group'):t('Personal','Personal')}</span><h3>${esc(e.title)}</h3><p>${fmtDateTime(e.start)} · ${esc(e.location||t('Sin ubicación','No location'))}<br>${esc(e.description||'')}</p><div class="agenda-card-actions"><button class="mini-button" data-action="share-event" data-event-id="${e.id}">${t('Compartir','Share')}</button>${e.type!=='official'?`<button class="mini-button" data-action="delete-event" data-event-id="${e.id}">${t('Eliminar','Delete')}</button>`:''}</div></div></article>`}).join(''):`<div class="empty-state"><span>□</span>${t('No hay eventos en esta vista.','There are no events in this view.')}</div>`}
byId('agendaFilters').addEventListener('click',e=>{const b=e.target.closest('[data-agenda-filter]');if(!b)return;state.agendaFilter=b.dataset.agendaFilter;saveState();$$('#agendaFilters button').forEach(x=>x.classList.toggle('active',x===b));renderAgenda()});
byId('addEventBtn').addEventListener('click',()=>openEventForm());byId('shareAgendaBtn').addEventListener('click',()=>{const next=combinedEvents().filter(e=>new Date(e.start)>new Date()).sort((a,b)=>new Date(a.start)-new Date(b.start)).slice(0,5);shareText('Próximos planes Erasmus',next.map(e=>`${fmtDateTime(e.start)} — ${e.title} (${e.location||'sin ubicación'})`).join('\n'),location.href)});
function openEventForm(prefill={}){openModal(`<h2>${t('Añadir plan','Add plan')}</h2><div class="form-grid"><label class="field-label">${t('Título','Title')}<input id="eventTitle" maxlength="70" value="${esc(prefill.title||'')}"></label><label class="field-label">${t('Fecha y hora','Date and time')}<input id="eventDate" type="datetime-local" value="${esc(prefill.date||'')}"></label><label class="field-label">${t('Lugar','Place')}<input id="eventLocation" maxlength="80" value="${esc(prefill.location||'')}"></label><label class="field-label">${t('Descripción','Description')}<textarea id="eventDescription" maxlength="300">${esc(prefill.description||'')}</textarea></label><label class="field-label">${t('Visibilidad','Visibility')}<select id="eventVisibility"><option value="personal">${t('Solo en mi dispositivo','Only on my device')}</option>${state.groupCode?`<option value="group">${t('Compartir con mi grupo','Share with my group')}</option>`:''}</select></label><button class="primary-button" data-action="save-event">${t('Guardar plan','Save plan')}</button></div>`)}
async function saveEvent(){const title=byId('eventTitle').value.trim(),start=byId('eventDate').value,locationText=byId('eventLocation').value.trim(),description=byId('eventDescription').value.trim(),type=byId('eventVisibility').value;if(!title||!start)return toast('Completa título y fecha.');const rec={id:uid(),title,start:new Date(start).toISOString(),end:new Date(start).toISOString(),location:locationText,description,type};if(type==='group'&&state.groupCode&&firebaseReady){try{await db.collection('groups').doc(state.groupCode).collection('plans').doc(rec.id).set({...rec,author:state.nickname||'Erasmus',createdAt:firebase.firestore.FieldValue.serverTimestamp()});await loadGroupPlans()}catch(e){toast('No se pudo compartir; guardado como personal.');rec.type='personal';state.personalEvents.push(rec)}}else state.personalEvents.push(rec);saveState();closeModal();renderAgenda();renderHome();toast('Plan guardado.')}
function findEvent(id){return combinedEvents().find(e=>e.id===id)}
function shareEvent(e){shareText(e.title,`${fmtDateTime(e.start)}\n${e.location||''}\n${e.description||''}`,location.href)}
async function deleteEvent(e){if(e.type==='group'&&firebaseReady&&state.groupCode){try{await db.collection('groups').doc(state.groupCode).collection('plans').doc(e.id).delete();await loadGroupPlans()}catch{toast('No se pudo eliminar.')}}else state.personalEvents=state.personalEvents.filter(x=>x.id!==e.id);saveState();renderAgenda();renderHome()}

let groupPlansCache=[];
async function loadGroupPlans(){groupPlansCache=[];if(state.groupCode&&firebaseReady){try{const s=await db.collection('groups').doc(state.groupCode).collection('plans').orderBy('start','asc').limit(100).get();groupPlansCache=s.docs.map(d=>({id:d.id,...d.data(),type:'group'}))}catch(e){console.warn(e)}}renderAgenda();renderHome()}
function groupHtml(){if(!state.groupCode)return`<p>${t('Crea un grupo privado para convertir rutas en quedadas y tener los próximos planes en un mismo lugar.','Create a private group to turn routes into meetups and keep upcoming plans together.')}</p><button class="primary-button" data-action="manage-group">${t('Crear o unirme','Create or join')}</button>`;return`<span class="eyebrow" style="color:var(--terracotta)">${t('Código','Code')} ${esc(state.groupCode)}</span><h3>${esc(state.localGroup?.name||'Grupo Erasmus')}</h3><p>${t('Comparte este código para que tus amigos vean y añadan planes a la agenda común.','Share this code so friends can see and add plans to the shared calendar.')}</p><div class="sheet-actions"><button class="primary-button" data-action="share-group">${t('Compartir código','Share code')}</button><button class="secondary-button" data-action="manage-group">${t('Gestionar','Manage')}</button></div>`}
function openGroupManager(){openModal(`<h2>Grupos privados</h2>${state.groupCode?`<p>Estás en el grupo <b>${esc(state.localGroup?.name||state.groupCode)}</b>.</p><div class="modal-actions"><button class="secondary-button" data-action="share-group">Compartir código</button><button class="primary-button" data-action="leave-group">Salir</button></div>`:`<div class="form-grid"><label class="field-label">Crear grupo<input id="newGroupName" placeholder="Ej.: Españoles Olomouc"></label><button class="primary-button" data-action="create-group">Crear grupo</button><hr style="width:100%;border:0;border-top:1px solid var(--line)"><label class="field-label">Unirme con código<input id="joinGroupCode" maxlength="8" placeholder="ABC123"></label><button class="secondary-button" data-action="join-group">Unirme</button></div>`}`)}
function makeGroupCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
async function createGroup(){const name=byId('newGroupName').value.trim();if(!name)return toast('Escribe un nombre.');const code=makeGroupCode();state.groupCode=code;state.localGroup={name};saveState();if(firebaseReady){try{await db.collection('groups').doc(code).set({name,createdAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:getDeviceId()});await syncPlayer()}catch(e){console.warn(e)}}closeModal();renderProfile();loadGroupPlans();toast(`Grupo creado: ${code}`)}
async function joinGroup(){const code=byId('joinGroupCode').value.trim().toUpperCase();if(code.length<4)return toast('Código no válido.');let name='Grupo Erasmus';if(firebaseReady){try{const d=await db.collection('groups').doc(code).get();if(!d.exists)return toast('No existe ese grupo.');name=d.data().name||name}catch(e){return toast('No se pudo comprobar el grupo.')}}state.groupCode=code;state.localGroup={name};saveState();await syncPlayer();closeModal();renderProfile();loadGroupPlans();toast('Te has unido al grupo.')}
function leaveGroup(){state.groupCode='';state.localGroup=null;groupPlansCache=[];saveState();closeModal();renderProfile();renderAgenda();toast('Has salido del grupo.')}

async function renderProfile(){const photos=await allPhotos(),verified=PLACES.filter(p=>isVerified(p)).length,visited=PLACES.filter(isVisited).length,plans=state.personalEvents.length,labels=setupLabels();byId('profileAvatar').textContent=(state.nickname||'?').slice(0,1).toUpperCase();byId('profileTitle').textContent=state.nickname||t('Tu experiencia','Your experience');byId('profileSummary').textContent=[labels.residence,labels.faculty].filter(Boolean).join(' · ')||t('Personaliza tu base para completar tu pasaporte.','Personalise your base to complete your passport.');byId('profilePoints').textContent=visited;byId('profileVisits').textContent=plans;byId('profileVerified').textContent=verified;byId('profilePhotos').textContent=photos.length;byId('groupPanel').innerHTML=groupHtml();byId('missionsList').innerHTML=MISSIONS.map(m=>{const p=missionProgress(m);return`<article class="mission-card"><div class="mission-card-head"><span>${m.icon}</span><h3>${esc(m.name)}</h3><small>${p.done}/${p.target}</small></div><div class="mission-progress"><span style="width:${p.pct}%"></span></div><small>${esc(m.description)}</small></article>`}).join('');byId('photoGallery').innerHTML=photos.length?photos.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(x=>`<button class="photo-tile" data-action="photo-view" data-photo-id="${x.id}"><img src="${x.data}" alt="${t('Foto de','Photo of')} ${esc(placeById(x.placeId)?.name||t('visita','visit'))}"><span>${esc(placeById(x.placeId)?.name||t('Visita','Visit'))}</span></button>`).join(''):`<div class="empty-state" style="grid-column:1/-1">${t('Aún no has guardado recuerdos.','You have not saved any memories yet.')}</div>`}
byId('editNameBtn').addEventListener('click',()=>openNameEditor());function openNameEditor(){openModal(`<h2>Tu nombre</h2><div class="form-grid"><label class="field-label">Nombre visible<input id="nicknameInput" maxlength="24" value="${esc(state.nickname)}"></label><button class="primary-button" data-action="save-name">Guardar</button></div>`)}
async function saveName(){const n=byId('nicknameInput').value.trim();if(!n)return toast('Escribe un nombre.');state.nickname=n;saveState();await syncPlayer();closeModal();renderProfile();toast('Nombre actualizado.')}

function openTransport(){openModal(`<h2>${t('Transporte y facultades','Transport and faculties')}</h2><p><b>${t('Billete','Ticket')}:</b> ${esc(D.transport.ticket)} · ${esc(D.transport.ticketValidity)}. ${t('Billete de 24 h','24-hour ticket')}: ${esc(D.transport.dayTicket)}.</p><div class="transport-table"><div class="transport-row header"><span>${t('Destino','Destination')}</span><span>${t('Desde Neředín','From Neředín')}</span><span>${t('Desde Envelopa','From Envelopa')}</span></div>${D.facultyTravel.map(x=>`<button class="transport-row" data-action="transport-place" data-place-name="${esc(x.placeName)}" style="border:0;text-align:left"><strong>${esc(state.language==='en'&&x.name==='Facultad de Artes (Filosofía y Letras)'?'Faculty of Arts':x.name)}</strong><span>${esc(x.fromNeredin)}</span><span>${esc(x.fromEnvelopa)}</span></button>`).join('')}</div><p><small>${esc(D.transport.note)}</small></p><div class="modal-actions"><button class="primary-button" data-action="external" data-url="${D.transport.officialUrl}">${t('Abrir DPMO','Open DPMO')}</button><button class="secondary-button" data-action="between-dorms">${t('Ruta residencias','Route between dorms')}</button></div>`)}
function openEmergency(){openModal(`<h2>${t('Emergencias','Emergencies')}</h2><p>${t('En una situación urgente, llama primero. Después puedes compartir tu posición actual con el grupo o con una persona de confianza.','In an emergency, call first. You can then share your current location with your group or someone you trust.')}</p><div class="emergency-grid">${D.emergency.map(x=>`<a class="emergency-call" href="tel:${x.number}"><strong>${x.number}</strong><span>${esc(x.label)}</span><small>${esc(x.detail)}</small></a>`).join('')}</div><div class="modal-actions"><button class="primary-button" data-action="share-location">${t('Compartir mi ubicación','Share my location')}</button><button class="secondary-button" data-action="hospital">${t('Ver hospital','View hospital')}</button></div>`)}
function openOffline(){openModal(`<h2>${t('Modo sin conexión','Offline mode')}</h2><p>${t('La aplicación, las rutas, la agenda y tus visitas funcionan sin red. El mapa conserva las teselas que ya hayas abierto.','The app, routes, calendar and your visits work offline. The map keeps the tiles you have already opened.')}</p><div class="card-panel"><b>${t('Estado actual','Current status')}:</b> ${navigator.onLine?t('en línea','online'):t('sin conexión','offline')}<br><small>${t('Para una excursión, abre antes la zona del mapa que vas a utilizar.','Before a trip, open the map area you plan to use.')}</small></div><div class="modal-actions"><button class="primary-button" data-action="prefetch-map">${t('Preparar mapa de Olomouc','Prepare Olomouc map')}</button><button class="secondary-button" data-action="install">${t('Instalar app','Install app')}</button></div>`)}
function prefetchMap(){toast('Guardando mapa básico…');const center={lat:49.594,lng:17.252},urls=[];for(let z=12;z<=15;z++){const n=2**z,x=Math.floor((center.lng+180)/360*n),latRad=center.lat*Math.PI/180,y=Math.floor((1-Math.asinh(Math.tan(latRad))/Math.PI)/2*n),r=z<14?1:2;for(let dx=-r;dx<=r;dx++)for(let dy=-r;dy<=r;dy++)urls.push(`https://a.tile.openstreetmap.org/${z}/${x+dx}/${y+dy}.png`)}Promise.allSettled(urls.map(u=>fetch(u,{mode:'no-cors'}))).then(()=>toast('Mapa básico preparado para uso sin conexión.'))}

function openSheet(html){byId('sheetContent').innerHTML=html;byId('bottomSheet').classList.add('open');byId('bottomSheet').setAttribute('aria-hidden','false');byId('sheetBackdrop').classList.add('open')}
function closeSheet(){byId('bottomSheet').classList.remove('open');byId('bottomSheet').setAttribute('aria-hidden','true');byId('sheetBackdrop').classList.remove('open')}
function openModal(html){byId('modalContent').innerHTML=html;byId('modal').classList.add('open');byId('modal').setAttribute('aria-hidden','false');byId('modalBackdrop').classList.add('open')}
function closeModal(){byId('modal').classList.remove('open');byId('modal').setAttribute('aria-hidden','true');byId('modalBackdrop').classList.remove('open')}
byId('closeSheet').addEventListener('click',closeSheet);byId('sheetBackdrop').addEventListener('click',closeSheet);byId('closeModal').addEventListener('click',closeModal);byId('modalBackdrop').addEventListener('click',closeModal);

// Global actions
function actionHandler(e){
  const a=e.target.closest('[data-action]');if(!a)return;const act=a.dataset.action;
  if(act==='edit-setup')openSetup();
  else if(act==='save-setup')saveSetup();
  else if(act==='arrival-toggle'){state.arrivalTasks[a.dataset.taskId]=!state.arrivalTasks[a.dataset.taskId];saveState();renderHome();renderProfile();}
  else if(act==='show-arrival'){setView('home');setTimeout(()=>byId('arrivalTitle')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}
  else if(act==='route-detail')openRoute(ROUTES.find(r=>r.id===a.dataset.routeId));
  else if(act==='share-route')shareRoute(ROUTES.find(r=>r.id===a.dataset.routeId));
  else if(act==='show-route-map')showRouteMap(ROUTES.find(r=>r.id===a.dataset.routeId));
  else if(act==='route-to-agenda'){const r=ROUTES.find(x=>x.id===a.dataset.routeId);closeSheet();openEventForm({title:r.name,location:r.placeNames[0]||'',description:`${r.duration} · ${r.budget}. ${r.description}`})}
  else if(act==='place-detail'){const p=placeById(a.dataset.placeId);if(p)openPlace(p)}
  else if(act==='visit')attemptVisit(placeById(a.dataset.placeId));
  else if(act==='save-unverified'){const p=placeById(a.dataset.placeId);state.visited[p.id]={visitedAt:new Date().toISOString(),verified:false};saveState();syncPlayer();closeModal();closeSheet();renderAll();toast('Lugar guardado en tu pasaporte.')}
  else if(act==='remove-visit'){delete state.visited[a.dataset.placeId];saveState();syncPlayer();closeModal();renderAll();toast('Visita eliminada.')}
  else if(act==='photo'){photoTarget=a.dataset.placeId;byId('photoInput').click()}
  else if(act==='directions'){const p=placeById(a.dataset.placeId);window.open(`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}`,'_blank','noopener')}
  else if(act==='share-place'){const p=placeById(a.dataset.placeId);shareText(p.name,`${p.note}\n${p.addr}\nPresupuesto: ${p.budgetLabel}`,`https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}`)}
  else if(act==='official'||act==='external')window.open(a.dataset.url,'_blank','noopener');
  else if(act==='comment')addComment(a.dataset.placeId);
  else if(act==='save-event')saveEvent();
  else if(act==='share-event'){const x=findEvent(a.dataset.eventId);if(x)shareEvent(x)}
  else if(act==='delete-event'){const x=findEvent(a.dataset.eventId);if(x)deleteEvent(x)}
  else if(act==='event-detail'){const x=findEvent(a.dataset.eventId);if(x)openModal(`<h2>${esc(x.title)}</h2><p>${fmtDateTime(x.start)} · ${esc(x.location||'')}</p><p>${esc(x.description||'')}</p><button class="primary-button" data-action="share-event" data-event-id="${x.id}">Compartir plan</button>`)}
  else if(act==='manage-group')openGroupManager();
  else if(act==='create-group')createGroup();else if(act==='join-group')joinGroup();else if(act==='leave-group')leaveGroup();
  else if(act==='share-group')shareText('Únete a mi grupo de Olomouc Quest',`Código del grupo: ${state.groupCode}`,location.href);
  else if(act==='save-name')saveName();
  else if(act==='cancel-modal')closeModal();
  else if(act==='transport-place'){const p=placeByName(a.dataset.placeName);if(p){closeModal();setView('map');setTimeout(()=>{initMap();map.flyTo([p.lat,p.lng],16);openPlace(p)},160)}}
  else if(act==='between-dorms')window.open(`https://www.google.com/maps/dir/?api=1&origin=${D.residences.neredin.lat},${D.residences.neredin.lng}&destination=${D.residences.envelopa.lat},${D.residences.envelopa.lng}&travelmode=transit`,'_blank','noopener');
  else if(act==='share-location')locateAndShare();else if(act==='hospital'){const p=PLACES.find(x=>x.cat==='health');if(p){closeModal();setView('map');setTimeout(()=>{initMap();map.flyTo([p.lat,p.lng],16);openPlace(p)},160)}}
  else if(act==='prefetch-map')prefetchMap();else if(act==='install'){if(deferredPrompt)byId('installBtn').click();else toast('Usa “Añadir a pantalla de inicio” en el menú del navegador.')}
  else if(act==='photo-view'){allPhotos().then(ps=>{const p=ps.find(x=>x.id===a.dataset.photoId);if(p)openModal(`<h2>${esc(placeById(p.placeId)?.name||'Recuerdo')}</h2><img src="${p.data}" alt="Foto de visita" style="width:100%;border-radius:16px">`)})}
}
document.addEventListener('click',actionHandler);
document.addEventListener('click',e=>{const v=e.target.closest('[data-vote]');if(v&&currentPlaceId)toggleVote(currentPlaceId,v.dataset.vote);const s=e.target.closest('[data-status-report]');if(s&&currentPlaceId)setStatusReport(currentPlaceId,s.dataset.statusReport)});
function locateAndShare(){if(!navigator.geolocation)return toast('Ubicación no disponible.');navigator.geolocation.getCurrentPosition(pos=>shareText('Mi ubicación',`Estoy aquí: ${pos.coords.latitude.toFixed(6)}, ${pos.coords.longitude.toFixed(6)}`,`https://www.google.com/maps?q=${pos.coords.latitude},${pos.coords.longitude}`),()=>toast('No se pudo obtener la ubicación.'),{enableHighAccuracy:true,timeout:10000})}

byId('emergencyBtn').addEventListener('click',openEmergency);byId('emergencyProfile').addEventListener('click',openEmergency);byId('transportHome').addEventListener('click',openTransport);byId('transportProfile').addEventListener('click',openTransport);byId('groupsHome').addEventListener('click',openGroupManager);byId('groupManageBtn').addEventListener('click',openGroupManager);byId('offlineProfile').addEventListener('click',openOffline);
byId('resetBtn').addEventListener('click',()=>{if(confirm('¿Borrar pasaporte, preferencias, comentarios y planes personales? Las fotos se conservan.')){state=defaultState();saveState();location.reload()}});

function renderAll(){renderHome();if(map){renderMapFilters();renderMapMarkers()}renderAgenda();renderProfile()}
applyLanguage();renderRoutes();renderHome();renderAgenda();renderProfile();loadGroupPlans();syncPlayer();
})();
