window.OQ_DATA = {
  "cats": {
    "essential": {
      "label": "Erasmus esenciales",
      "icon": "🧩",
      "color": "#2F6570",
      "points": 1,
      "family": "useful"
    },
    "canteen": {
      "label": "Comedores UP",
      "icon": "🥣",
      "color": "#9A6A32",
      "points": 1,
      "family": "food"
    },
    "health": {
      "label": "Salud y urgencias",
      "icon": "🏥",
      "color": "#A4494F",
      "points": 1,
      "family": "useful"
    },
    "service": {
      "label": "Servicios útiles",
      "icon": "🛠️",
      "color": "#68727A",
      "points": 1,
      "family": "useful"
    },
    "bar": {
      "label": "Bares",
      "icon": "🍸",
      "color": "#8E4C65",
      "points": 10,
      "family": "night"
    },
    "club": {
      "label": "Discotecas",
      "icon": "🪩",
      "color": "#6E4B83",
      "points": 10,
      "family": "night"
    },
    "gym": {
      "label": "Gimnasios",
      "icon": "💪",
      "color": "#3F7659",
      "points": 2,
      "family": "nature"
    },
    "dorm": {
      "label": "Residencias",
      "icon": "🏠",
      "color": "#476A7C",
      "points": 1,
      "family": "useful"
    },
    "faculty": {
      "label": "Facultades UP",
      "icon": "🎓",
      "color": "#445C8A",
      "points": 1,
      "family": "useful"
    },
    "market": {
      "label": "Supermercados",
      "icon": "🛒",
      "color": "#5D7B58",
      "points": 1,
      "family": "useful"
    },
    "restaurant": {
      "label": "Restaurantes",
      "icon": "🍽️",
      "color": "#B56C3C",
      "points": 10,
      "family": "food"
    },
    "cafe": {
      "label": "Cafés",
      "icon": "☕",
      "color": "#795A43",
      "points": 10,
      "family": "food"
    },
    "park": {
      "label": "Parques",
      "icon": "🌳",
      "color": "#3D7650",
      "points": 10,
      "family": "nature"
    },
    "landmark": {
      "label": "Puntos de interés",
      "icon": "🏛️",
      "color": "#A37A36",
      "points": 15,
      "family": "culture"
    },
    "museum": {
      "label": "Museos",
      "icon": "🖼️",
      "color": "#7C568B",
      "points": 15,
      "family": "culture"
    },
    "church": {
      "label": "Iglesias",
      "icon": "⛪",
      "color": "#8A6C4B",
      "points": 15,
      "family": "culture"
    },
    "viewpoint": {
      "label": "Miradores y montaña",
      "icon": "⛰️",
      "color": "#367487",
      "points": 20,
      "family": "nature"
    },
    "secret": {
      "label": "Secretos",
      "icon": "🗝️",
      "color": "#70445F",
      "points": 25,
      "family": "culture"
    },
    "activity": {
      "label": "Actividades",
      "icon": "🎯",
      "color": "#3E6F91",
      "points": 15,
      "family": "nature"
    },
    "ski": {
      "label": "Montaña y nieve",
      "icon": "🎿",
      "color": "#4387A0",
      "points": 30,
      "family": "nature"
    },
    "daytrip": {
      "label": "Excursiones",
      "icon": "🚗",
      "color": "#B65D47",
      "points": 30,
      "family": "trip"
    },
    "freetour": {
      "label": "Tours e información",
      "icon": "🧭",
      "color": "#9E793C",
      "points": 5,
      "family": "culture"
    },
    "town": {
      "label": "Pueblos cercanos",
      "icon": "🏘️",
      "color": "#65727B",
      "points": 20,
      "family": "trip"
    }
  },
  "places": [
    {
      "name": "Centro Erasmus UPOL (Welcome Office + Mobility + ESN)",
      "cat": "essential",
      "lat": 49.5961908,
      "lng": 17.2542964,
      "rating": null,
      "addr": "Vodární 601/6",
      "hours": "Welcome Office: L–J 12:00–17:00; V 9:00–15:00. ESN: con cita",
      "note": "Primer punto de ayuda para estudiantes internacionales. En el mismo edificio están Welcome Office, Office for Mobility y ESN UP Olomouc.",
      "tags": [
        "erasmus",
        "ayuda",
        "esn",
        "movilidad",
        "welcome"
      ],
      "lastVerified": "25/07/2026",
      "radius": 180,
      "officialUrl": "https://www.upol.cz/welcome-office/",
      "id": "centro-erasmus-upol-welcome-office-mobility-esn",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 0,
      "budgetLabel": "Gratis",
      "statusType": "verify",
      "statusText": "Horario por confirmar"
    },
    {
      "name": "UPoint – información y tienda de la universidad",
      "cat": "essential",
      "lat": 49.5938872,
      "lng": 17.2526275,
      "rating": null,
      "addr": "Horní náměstí 205/12",
      "hours": "L–V 9:00–17:00",
      "note": "Centro de información de UPOL, tienda universitaria y espacio tranquilo de lectura o estudio. Descuento para estudiantes UP.",
      "tags": [
        "información",
        "universidad",
        "tienda",
        "estudio"
      ],
      "lastVerified": "25/07/2026",
      "radius": 150,
      "officialUrl": "https://upoint.upol.cz/kontakt/",
      "id": "upoint-informacion-y-tienda-de-la-universidad",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "verify",
      "statusText": "Horario por confirmar"
    },
    {
      "name": "Zbrojnice – biblioteca 24h + oficina ISIC",
      "cat": "essential",
      "lat": 49.5957004,
      "lng": 17.2601165,
      "rating": null,
      "addr": "Biskupské nám. 842/1",
      "hours": "Biblioteca L–J 8:00–22:00; V 8:00–19:00; S 9:00–16:00. Sala nocturna 24h",
      "note": "Biblioteca central, salas de estudio y oficina de tarjetas UP/ISIC en la planta baja. Para la sala nocturna necesitas la tarjeta UPOL.",
      "tags": [
        "biblioteca",
        "isic",
        "tarjeta",
        "estudio",
        "24h"
      ],
      "lastVerified": "25/07/2026",
      "radius": 180,
      "officialUrl": "https://www.knihovna.upol.cz/en/branches/zbrojnice-armoury/",
      "id": "zbrojnice-biblioteca-24h-oficina-isic",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 0,
      "budgetLabel": "Gratis",
      "statusType": "always",
      "statusText": "Abierto 24 h"
    },
    {
      "name": "DPMO – abonos y tarjetas de transporte",
      "cat": "essential",
      "lat": 49.5959451,
      "lng": 17.2468983,
      "rating": null,
      "addr": "Legionářská 746/1",
      "hours": "L–V 6:00–18:00; S 7:00–12:00",
      "note": "Oficina principal para abonos de 7 días a 12 meses, tarjetas y gestiones de transporte urbano. Lleva identificación e ISIC.",
      "tags": [
        "transporte",
        "abono",
        "tranvía",
        "bus",
        "isic"
      ],
      "lastVerified": "25/07/2026",
      "radius": 180,
      "officialUrl": "https://www.dpmo.cz/en/information-for-passengers/ticket-offices/",
      "id": "dpmo-abonos-y-tarjetas-de-transporte",
      "scope": "city",
      "points": 1,
      "budgetMin": 25,
      "budgetMax": 230,
      "budgetLabel": "25–230 CZK",
      "statusType": "verify",
      "statusText": "Horario por confirmar"
    },
    {
      "name": "Oficina de alojamiento internacional UP",
      "cat": "essential",
      "lat": 49.591851,
      "lng": 17.2649684,
      "rating": null,
      "addr": "Generál Svoboda, Šmeralova 1122/12, oficina C.1.12",
      "hours": "L–V; consultar horario vigente",
      "note": "Gestiones de alojamiento de estudiantes internacionales, incidencias administrativas y consultas sobre residencias UP.",
      "tags": [
        "alojamiento",
        "residencia",
        "iskam",
        "internacional"
      ],
      "lastVerified": "25/07/2026",
      "radius": 200,
      "id": "oficina-de-alojamiento-internacional-up",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir"
    },
    {
      "name": "Centro de apoyo y orientación para estudiantes",
      "cat": "essential",
      "lat": 49.5957087,
      "lng": 17.2646513,
      "rating": null,
      "addr": "Žižkovo náměstí 5",
      "hours": "Con cita",
      "note": "Punto de acceso a apoyo para estudiantes con necesidades específicas y a servicios universitarios de orientación psicológica, académica y de salud.",
      "tags": [
        "apoyo",
        "psicología",
        "accesibilidad",
        "orientación"
      ],
      "lastVerified": "25/07/2026",
      "radius": 180,
      "officialUrl": "https://cps.upol.cz/en/",
      "id": "centro-de-apoyo-y-orientacion-para-estudiantes",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "verify",
      "statusText": "Horario por confirmar"
    },
    {
      "name": "Parada Neředín, krematorium",
      "cat": "essential",
      "lat": 49.5953,
      "lng": 17.2174,
      "rating": null,
      "addr": "Terminal de tranvía de Neředín",
      "hours": "Según DPMO",
      "note": "Parada clave de Neředín. Las líneas 2 y 7 conectan el campus con el centro y Hlavní nádraží.",
      "tags": [
        "neredin",
        "tranvía",
        "línea 2",
        "línea 7"
      ],
      "radius": 180,
      "points": 1,
      "id": "parada-neredin-krematorium",
      "scope": "city",
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026"
    },
    {
      "name": "Parada Envelopa",
      "cat": "essential",
      "lat": 49.5896,
      "lng": 17.2629,
      "rating": null,
      "addr": "Envelopa, junto a 17. listopadu",
      "hours": "Según DPMO",
      "note": "Parada práctica del campus de Envelopa, conectada con la estación y el centro. Desde la estación también se puede caminar unos 15 minutos.",
      "tags": [
        "envelopa",
        "tranvía",
        "estación"
      ],
      "radius": 180,
      "points": 1,
      "id": "parada-envelopa",
      "scope": "city",
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026"
    },
    {
      "name": "Menza 17. listopadu",
      "cat": "canteen",
      "lat": 49.5946647,
      "lng": 17.2654179,
      "rating": null,
      "addr": "Tř. 17. listopadu 1083/54",
      "hours": "L–V 11:00–14:30 en periodo lectivo",
      "note": "El comedor universitario más grande. Cocina checa e internacional, pizza, opciones vegetarianas, veganas y sin gluten.",
      "tags": [
        "menza",
        "comedor",
        "barato",
        "vegano",
        "sin gluten"
      ],
      "lastVerified": "25/07/2026",
      "radius": 180,
      "officialUrl": "https://skm.upol.cz/en/dining/17-listopadu-canteen/",
      "id": "menza-17-listopadu",
      "scope": "city",
      "points": 1,
      "budgetMin": 80,
      "budgetMax": 180,
      "budgetLabel": "80–180 CZK",
      "statusType": "verify",
      "statusText": "Horario por confirmar"
    },
    {
      "name": "Menza Křížkovského",
      "cat": "canteen",
      "lat": 49.5953011,
      "lng": 17.258647,
      "rating": null,
      "addr": "Křížkovského 8",
      "hours": "L–V 11:00–14:30 en periodo lectivo",
      "note": "Comedor universitario céntrico, útil para quienes estudian en Filosofía, Teología o edificios del casco histórico.",
      "tags": [
        "menza",
        "comedor",
        "centro",
        "barato"
      ],
      "lastVerified": "25/07/2026",
      "radius": 180,
      "officialUrl": "https://skm.upol.cz/en/dining/krizkovskeho-canteen/",
      "id": "menza-krizkovskeho",
      "scope": "city",
      "points": 1,
      "budgetMin": 80,
      "budgetMax": 180,
      "budgetLabel": "80–180 CZK",
      "statusType": "verify",
      "statusText": "Horario por confirmar"
    },
    {
      "name": "Menza Neředín",
      "cat": "canteen",
      "lat": 49.5946057,
      "lng": 17.2142508,
      "rating": null,
      "addr": "Tř. Míru 115, campus Neředín",
      "hours": "L–V 11:00–14:30; bistró desde 7:30",
      "note": "Comedor del campus de Neředín, cerca de las residencias y de la Facultad de Cultura Física.",
      "tags": [
        "menza",
        "comedor",
        "neredin",
        "barato"
      ],
      "lastVerified": "25/07/2026",
      "radius": 230,
      "officialUrl": "https://skm.upol.cz/en/dining/neredin-canteen/",
      "id": "menza-neredin",
      "scope": "city",
      "points": 1,
      "budgetMin": 80,
      "budgetMax": 180,
      "budgetLabel": "80–180 CZK",
      "statusType": "verify",
      "statusText": "Horario por confirmar"
    },
    {
      "name": "FreshUP+ – cena y comida de tarde",
      "cat": "canteen",
      "lat": 49.5941008,
      "lng": 17.2665114,
      "rating": null,
      "addr": "Šmeralova 1084/6",
      "hours": "Laborables, normalmente 14:00–19:30",
      "note": "Formato híbrido de bistró y comedor en la antigua menza Josef Jařab; útil cuando las menzas de mediodía ya han cerrado.",
      "tags": [
        "freshup",
        "cena",
        "comedor",
        "tarde",
        "residencias"
      ],
      "lastVerified": "25/07/2026",
      "radius": 180,
      "officialUrl": "https://skm.upol.cz/en/dining/freshup/",
      "id": "freshup-cena-y-comida-de-tarde",
      "scope": "city",
      "points": 1,
      "budgetMin": 80,
      "budgetMax": 180,
      "budgetLabel": "80–180 CZK",
      "statusType": "verify",
      "statusText": "Horario por confirmar"
    },
    {
      "name": "Hospital Universitario – urgencias y farmacia 24",
      "cat": "health",
      "lat": 49.586792,
      "lng": 17.239369,
      "rating": null,
      "addr": "Zdravotníků 248/7",
      "hours": "Urgencias de adultos: laborables 15:00–7:00; fines de semana y festivos 24h",
      "note": "Campus del hospital universitario. Alberga urgencias de adultos y Lékárna 24. En una emergencia grave llama al 112 o 155.",
      "tags": [
        "urgencias",
        "hospital",
        "farmacia",
        "24h",
        "salud"
      ],
      "lastVerified": "25/07/2026",
      "radius": 450,
      "officialUrl": "https://www.fnol.cz/en/emergency-medical-service-ambulance",
      "id": "hospital-universitario-urgencias-y-farmacia-24",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 0,
      "budgetLabel": "Emergencia",
      "statusType": "always",
      "statusText": "Abierto 24 h"
    },
    {
      "name": "Estación de tren de Olomouc",
      "cat": "service",
      "points": 1,
      "lat": 49.5925769,
      "lng": 17.2778661,
      "rating": 4,
      "addr": "Jeremenkova 103/23",
      "hours": "24h",
      "note": "Nudo principal para Praga, Brno, Ostrava y muchas escapadas. Desde Envelopa son dos paradas de tranvía; desde Neředín, tranvías 2 o 7.",
      "tags": [
        "tren",
        "viajes",
        "envelopa",
        "neredin",
        "hlavní nádraží"
      ],
      "id": "estacion-de-tren-de-olomouc",
      "scope": "city",
      "budgetMin": 0,
      "budgetMax": 0,
      "budgetLabel": "Gratis",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Estación central de autobuses",
      "cat": "service",
      "lat": 49.5881,
      "lng": 17.2857,
      "rating": null,
      "addr": "Sladkovského, Olomouc",
      "hours": "Según servicio",
      "note": "Salida de autobuses regionales y de larga distancia. Está conectada con la estación de tren mediante transporte urbano.",
      "tags": [
        "bus",
        "autobús",
        "viajes",
        "estación"
      ],
      "lastVerified": "25/07/2026",
      "radius": 300,
      "id": "estacion-central-de-autobuses",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir"
    },
    {
      "name": "Campus Neředín (residencias Erasmus)",
      "id": "residencias-de-neredin",
      "cat": "dorm",
      "lat": 49.59449,
      "lng": 17.21605,
      "rating": null,
      "addr": "U Letiště / tř. Míru, Neředín",
      "hours": "24h",
      "note": "Base social de muchos Erasmus: residencias modernas, cocina compartida, Menza y tranvía al centro en unos 15 minutos.",
      "tags": [
        "neredin",
        "residencia",
        "erasmus",
        "base"
      ],
      "radius": 500,
      "points": 1,
      "scope": "city",
      "budgetMin": 0,
      "budgetMax": 0,
      "budgetLabel": "Gratis",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026"
    },
    {
      "name": "Campus Envelopa (residencias Erasmus)",
      "id": "campus-envelopa",
      "cat": "dorm",
      "lat": 49.59265,
      "lng": 17.26565,
      "rating": null,
      "addr": "Šmeralova / 17. listopadu, Envelopa",
      "hours": "24h",
      "note": "Base céntrica junto a facultades, Menza, S-klub y el río. Muy cómoda para moverse andando y llegar a la estación.",
      "tags": [
        "envelopa",
        "residencia",
        "erasmus",
        "base"
      ],
      "radius": 550,
      "points": 1,
      "scope": "city",
      "budgetMin": 0,
      "budgetMax": 0,
      "budgetLabel": "Gratis",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026"
    },
    {
      "name": "Albert Šantovka",
      "cat": "market",
      "lat": 49.5864602,
      "lng": 17.2589224,
      "rating": 4.1,
      "addr": "Polská 1",
      "hours": "7:00–22:00",
      "note": "La compra más cómoda desde Envelopa: dentro de Šantovka y a unos 10 minutos andando. Ideal para compras frecuentes.",
      "id": "albert-polska",
      "tags": [
        "envelopa",
        "compra",
        "centro comercial",
        "diario"
      ],
      "lastVerified": "25/07/2026",
      "scope": "city",
      "points": 1,
      "budgetMin": 100,
      "budgetMax": 800,
      "budgetLabel": "Según compra",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "radius": 250
    },
    {
      "name": "Globus Olomouc",
      "cat": "market",
      "lat": 49.6015311,
      "lng": 17.2230799,
      "rating": 4.4,
      "addr": "Pražská 248/39",
      "hours": "7:00–21:00",
      "note": "La compra grande típica desde Neředín: enorme surtido y restaurante. Antiguos Erasmus recomiendan mochila porque se llega andando en unos 15 minutos.",
      "tags": [
        "neredin",
        "compra grande",
        "hipermercado",
        "restaurante"
      ],
      "lastVerified": "25/07/2026",
      "id": "globus-olomouc",
      "scope": "city",
      "points": 1,
      "budgetMin": 100,
      "budgetMax": 800,
      "budgetLabel": "Según compra",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "radius": 250
    },
    {
      "name": "Kaufland Olomouc-Neředín",
      "cat": "market",
      "lat": 49.584399,
      "lng": 17.225256,
      "rating": 4.1,
      "addr": "Hněvotínská 984/56",
      "hours": "7:00–22:00",
      "note": "Alternativa de compra grande y económica para Neředín; además tiene farmacia, cajero y puntos de paquetería.",
      "tags": [
        "neredin",
        "compra grande",
        "barato",
        "farmacia"
      ],
      "lastVerified": "25/07/2026",
      "points": 1,
      "id": "kaufland-olomouc-neredin",
      "scope": "city",
      "budgetMin": 100,
      "budgetMax": 800,
      "budgetLabel": "Según compra",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "radius": 250
    },
    {
      "name": "Lidl Velkomoravská",
      "cat": "market",
      "lat": 49.582231,
      "lng": 17.248341,
      "rating": 4.2,
      "addr": "Velkomoravská 488/29",
      "hours": "L–S 7:00–21:00; D 8:00–21:00",
      "note": "Opción de descuento útil al sur del centro. No es el más cercano a las residencias, pero sí una alternativa barata cuando se pasa por esa zona.",
      "tags": [
        "barato",
        "descuento",
        "sur"
      ],
      "lastVerified": "25/07/2026",
      "points": 1,
      "id": "lidl-velkomoravska",
      "scope": "city",
      "budgetMin": 100,
      "budgetMax": 800,
      "budgetLabel": "Según compra",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "radius": 250
    },
    {
      "name": "Facultad de Ciencias (Přírodovědecká fakulta)",
      "cat": "faculty",
      "lat": 49.5924087,
      "lng": 17.2631877,
      "rating": 4.7,
      "addr": "17. listopadu 12",
      "hours": "L–V 6:00–21:00",
      "note": "Terraza con vistas a toda la ciudad (Bistro B6).",
      "id": "facultad-de-ciencias-prirodovedecka-fakulta",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Facultad de Filosofía y Letras",
      "cat": "faculty",
      "lat": 49.5950116,
      "lng": 17.2597325,
      "rating": 4.8,
      "addr": "Křížkovského 10",
      "hours": "Horario académico",
      "note": "Edificio histórico junto al Rectorado.",
      "id": "facultad-de-filosofia-y-letras",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Facultad de Educación (Pedagogická fakulta)",
      "cat": "faculty",
      "lat": 49.5957087,
      "lng": 17.2646513,
      "rating": 4.5,
      "addr": "Žižkovo nám. 5",
      "hours": "Horario académico",
      "note": "Cafetería propia.",
      "id": "facultad-de-educacion-pedagogicka-fakulta",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Facultad de Medicina (Lékařská fakulta)",
      "cat": "faculty",
      "lat": 49.5862796,
      "lng": 17.2366108,
      "rating": 4.7,
      "addr": "Hněvotínská 976/3",
      "hours": "Horario académico",
      "note": "Campus sanitario en Nová Ulice.",
      "id": "facultad-de-medicina-lekarska-fakulta",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Facultad de Derecho (Právnická fakulta)",
      "cat": "faculty",
      "lat": 49.5904809,
      "lng": 17.2626714,
      "rating": 4.6,
      "addr": "17. listopadu 8",
      "hours": "Horario académico",
      "note": "Buffet muy valorado.",
      "id": "facultad-de-derecho-pravnicka-fakulta",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Facultad de Cultura Física y Deporte",
      "cat": "faculty",
      "lat": 49.5944519,
      "lng": 17.2134809,
      "rating": 4.5,
      "addr": "Tř. Míru 117, Neředín",
      "hours": "Horario académico",
      "note": "Instalaciones deportivas propias.",
      "id": "facultad-de-cultura-fisica-y-deporte",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Facultad de Teología Sts. Cirilo y Metodio",
      "cat": "faculty",
      "lat": 49.5947113,
      "lng": 17.2546998,
      "rating": 4.8,
      "addr": "Univerzitní nám. 22",
      "hours": "L–V 7:00–20:00",
      "note": "La más pequeña, ambiente cercano.",
      "id": "facultad-de-teologia-sts-cirilo-y-metodio",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Fashion Cocktail Bar",
      "cat": "bar",
      "lat": 49.5918626,
      "lng": 17.251204,
      "rating": 4.9,
      "addr": "Uhelná 1186/8",
      "hours": "Cierra ~2:00–3:00",
      "note": "Cócteles a medida en Uhelná. Buena opción para una noche tranquila; no hace falta duplicar dos bares en la misma dirección.",
      "tags": [
        "cócteles",
        "centro",
        "noche"
      ],
      "id": "fashion-cocktail-bar",
      "scope": "city",
      "points": 10,
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Jerry's Bar",
      "cat": "bar",
      "lat": 49.5936313,
      "lng": 17.252222,
      "rating": 4.8,
      "addr": "Horní nám. 202",
      "hours": "Cierra ~2:00",
      "note": "Pub céntrico y sencillo para empezar la noche en Horní náměstí.",
      "tags": [
        "cerveza",
        "centro",
        "estudiantes"
      ],
      "id": "jerry-s-bar",
      "scope": "city",
      "points": 10,
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "The Black Stuff Irish Pub",
      "cat": "bar",
      "lat": 49.5970496,
      "lng": 17.2614051,
      "rating": 4.8,
      "addr": "1. máje 807",
      "hours": "Cierra ~1:00–2:00 (cerrado dom)",
      "note": "Pub irlandés muy valorado; ambiente internacional y buena opción cuando no apetece discoteca.",
      "tags": [
        "pub",
        "internacional",
        "cerveza",
        "centro"
      ],
      "id": "the-black-stuff-irish-pub",
      "scope": "city",
      "points": 10,
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Bar Zahrada",
      "cat": "bar",
      "lat": 49.5901173,
      "lng": 17.2530631,
      "rating": 4.8,
      "addr": "Mlýnská 79",
      "hours": "14:00–00:00",
      "note": "Terraza-jardín, cerveza asequible y ambiente relajado. Encaja especialmente bien con un Erasmus más natural.",
      "tags": [
        "terraza",
        "jardín",
        "barato",
        "música"
      ],
      "id": "bar-zahrada",
      "scope": "city",
      "points": 10,
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Vertigo – studentský klub",
      "cat": "bar",
      "lat": 49.5952995,
      "lng": 17.2552141,
      "rating": 4.5,
      "addr": "Univerzitní nám. 6",
      "hours": "18:00–2:00",
      "note": "El clásico estudiantil de Olomouc: sótano, precios bajos y ambiente informal. Más bar universitario que gran discoteca.",
      "tags": [
        "erasmus",
        "estudiantes",
        "barato",
        "noche"
      ],
      "points": 12,
      "id": "vertigo-studentsky-klub",
      "scope": "city",
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Air Bar Neředín",
      "cat": "bar",
      "lat": 49.592489,
      "lng": 17.210744,
      "rating": 4.5,
      "addr": "Neředín 954, junto al aeródromo",
      "hours": "L–V 15:00–21:00; S–D 10:00–22:00 aprox.",
      "note": "El bar de proximidad para Neředín: terraza, aire libre y ambiente relajado. Mejor para tardeo que para salir de madrugada.",
      "tags": [
        "neredin",
        "terraza",
        "aire libre",
        "tardeo"
      ],
      "lastVerified": "25/07/2026",
      "points": 12,
      "id": "air-bar-neredin",
      "scope": "city",
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "radius": 250
    },
    {
      "name": "Belmondo Club",
      "cat": "club",
      "lat": 49.590805,
      "lng": 17.2514305,
      "rating": 4,
      "addr": "Mlýnská 938/4",
      "hours": "Jue–sáb 22:00–5:00/6:00",
      "note": "La gran discoteca Erasmus del centro, con varias salas. Lleva DNI o pasaporte físico; las opiniones sobre el control de acceso son mixtas.",
      "tags": [
        "erasmus",
        "discoteca",
        "centro",
        "dni"
      ],
      "points": 15,
      "id": "belmondo-club",
      "scope": "city",
      "budgetMin": 150,
      "budgetMax": 500,
      "budgetLabel": "150–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "S-klub",
      "cat": "club",
      "lat": 49.5939857,
      "lng": 17.262281,
      "rating": 4.3,
      "addr": "17. listopadu 43",
      "hours": "Según evento",
      "note": "Sala de conciertos y fiestas junto a Envelopa. Es especialmente relevante durante la Welcome Party y cuando hay evento programado.",
      "tags": [
        "envelopa",
        "conciertos",
        "welcome party",
        "eventos"
      ],
      "points": 12,
      "id": "s-klub",
      "scope": "city",
      "budgetMin": 150,
      "budgetMax": 500,
      "budgetLabel": "150–500 CZK",
      "statusType": "event",
      "statusText": "Solo con evento / consulta",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Varna Club",
      "cat": "club",
      "lat": 49.5944643,
      "lng": 17.2490528,
      "rating": 3.5,
      "addr": "Riegrova 9/6",
      "hours": "Jue–sáb 22:00–5:00",
      "note": "Club céntrico reabierto con dos salas y terraza. Mejor comprobar el evento concreto antes de ir.",
      "tags": [
        "discoteca",
        "terraza",
        "centro",
        "eventos"
      ],
      "points": 12,
      "id": "varna-club",
      "scope": "city",
      "budgetMin": 150,
      "budgetMax": 500,
      "budgetLabel": "150–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Restaurant U Mořice",
      "cat": "restaurant",
      "lat": 49.5947078,
      "lng": 17.2517126,
      "rating": 4.6,
      "addr": "Opletalova 364/1",
      "hours": "11:00–00:00",
      "note": "Prueba el 'kulajda'.",
      "id": "restaurant-u-morice",
      "scope": "city",
      "points": 10,
      "budgetMin": 180,
      "budgetMax": 500,
      "budgetLabel": "180–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Drapal Restaurant",
      "cat": "restaurant",
      "lat": 49.5916255,
      "lng": 17.2495384,
      "rating": 4.5,
      "addr": "Havlíčkova 637/1",
      "hours": "11:00–00:00",
      "note": "Cervecería muy popular, reserva recomendada.",
      "id": "drapal-restaurant",
      "scope": "city",
      "points": 10,
      "budgetMin": 180,
      "budgetMax": 500,
      "budgetLabel": "180–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Moravská restaurace",
      "cat": "restaurant",
      "lat": 49.5935623,
      "lng": 17.2503349,
      "rating": 4.5,
      "addr": "Horní nám. 23",
      "hours": "11:30–22:00",
      "note": "Vistas a la plaza principal.",
      "id": "moravska-restaurace",
      "scope": "city",
      "points": 10,
      "budgetMin": 180,
      "budgetMax": 500,
      "budgetLabel": "180–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Restaurace Stodola",
      "cat": "restaurant",
      "lat": 49.5954789,
      "lng": 17.2392953,
      "rating": 4.5,
      "addr": "Litovelská 77/7",
      "hours": "11:00–23:00/00:00",
      "note": "Comida checa contundente.",
      "id": "restaurace-stodola",
      "scope": "city",
      "points": 10,
      "budgetMin": 180,
      "budgetMax": 500,
      "budgetLabel": "180–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Long Story Short Eatery & Bakery",
      "cat": "restaurant",
      "lat": 49.597625,
      "lng": 17.2586546,
      "rating": 4.6,
      "addr": "Koželužská 31c/945",
      "hours": "8:00–22:00/23:00",
      "note": "Hostel de diseño + restaurante, un imprescindible.",
      "id": "long-story-short-eatery-bakery",
      "scope": "city",
      "points": 10,
      "budgetMin": 180,
      "budgetMax": 500,
      "budgetLabel": "180–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Café La Fée",
      "cat": "cafe",
      "lat": 49.5948447,
      "lng": 17.2526697,
      "rating": 4.6,
      "addr": "Ostružnická 13",
      "hours": "8:00–21:00",
      "note": "Jardín interior con mantas, desayunos.",
      "id": "cafe-la-fee",
      "scope": "city",
      "points": 10,
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Sophie's Café",
      "cat": "cafe",
      "lat": 49.5958782,
      "lng": 17.2552836,
      "rating": 4.6,
      "addr": "Denisova 292/33",
      "hours": "7:00–22:00",
      "note": "Ambiente acogedor, menú en inglés.",
      "id": "sophie-s-cafe",
      "scope": "city",
      "points": 10,
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Great Coffee & Wine",
      "cat": "cafe",
      "lat": 49.5881246,
      "lng": 17.2594414,
      "rating": 4.7,
      "addr": "Šantova 1222/7",
      "hours": "7:00–21:00",
      "note": "Buen espacio para estudiar.",
      "id": "great-coffee-wine",
      "scope": "city",
      "points": 10,
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Elite Café & Wine Bar",
      "cat": "cafe",
      "lat": 49.5929205,
      "lng": 17.2471792,
      "rating": 5,
      "addr": "Dánská 1148/5",
      "hours": "7:30–20:00/22:00",
      "note": "Muy buen café de especialidad.",
      "id": "elite-cafe-wine-bar",
      "scope": "city",
      "points": 10,
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Vnitro",
      "cat": "cafe",
      "lat": 49.5942022,
      "lng": 17.2490708,
      "rating": 5,
      "addr": "Riegrova 404/5",
      "hours": "15:00–00:00",
      "note": "Spot de verano con amigos.",
      "id": "vnitro",
      "scope": "city",
      "points": 10,
      "budgetMin": 80,
      "budgetMax": 300,
      "budgetLabel": "80–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Smetanovy sady",
      "cat": "park",
      "lat": 49.5878708,
      "lng": 17.2484178,
      "rating": 4.6,
      "addr": "Centro-oeste",
      "hours": "24h",
      "note": "El más grande, con faisanes.",
      "id": "smetanovy-sady",
      "scope": "city",
      "points": 10,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Bezručovy sady",
      "cat": "park",
      "lat": 49.5922622,
      "lng": 17.2562385,
      "rating": 4.7,
      "addr": "Junto a la muralla",
      "hours": "24h",
      "note": "Paseo junto al río y las murallas.",
      "id": "bezrucovy-sady",
      "scope": "city",
      "points": 10,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Čechovy sady",
      "cat": "park",
      "lat": 49.5927891,
      "lng": 17.2448288,
      "rating": 4.6,
      "addr": "Centro-oeste",
      "hours": "24h",
      "note": "Zona deportiva.",
      "id": "cechovy-sady",
      "scope": "city",
      "points": 10,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Park Rudolfova alej",
      "cat": "park",
      "lat": 49.5874035,
      "lng": 17.2513582,
      "rating": 4.7,
      "addr": "Sur del centro",
      "hours": "24h",
      "note": "Paseos largos y tranquilos.",
      "id": "park-rudolfova-alej",
      "scope": "city",
      "points": 10,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Reloj Astronómico de Olomouc",
      "cat": "landmark",
      "lat": 49.5940989,
      "lng": 17.2515349,
      "rating": 4.6,
      "addr": "Horní nám. 26",
      "hours": "Espectáculo a las 12:00",
      "note": "Motivos socialistas, único en el mundo.",
      "id": "reloj-astronomico-de-olomouc",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Columna de la Santísima Trinidad",
      "cat": "landmark",
      "lat": 49.5939307,
      "lng": 17.2504501,
      "rating": 4.8,
      "addr": "Horní náměstí",
      "hours": "24h",
      "note": "UNESCO, la columna barroca más alta de Europa Central.",
      "id": "columna-de-la-santisima-trinidad",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Universidad Palacký (edificio principal)",
      "cat": "landmark",
      "lat": 49.5954268,
      "lng": 17.2600153,
      "rating": 4.7,
      "addr": "Křížkovského 511/8",
      "hours": "Horario académico",
      "note": "Fundada en 1573.",
      "id": "universidad-palacky-edificio-principal",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Fuente de Hércules",
      "cat": "landmark",
      "lat": 49.5942,
      "lng": 17.251,
      "rating": 4.7,
      "addr": "Horní náměstí",
      "hours": "24h",
      "note": "De 1687, justo delante del Ayuntamiento — parte del conjunto único de fuentes barrocas de la ciudad.",
      "id": "fuente-de-hercules",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Fuente de Arión",
      "cat": "landmark",
      "lat": 49.5934,
      "lng": 17.2511,
      "rating": 4.7,
      "addr": "Horní náměstí",
      "hours": "24h",
      "note": "Obra de Ivan Theimer, con la gran tortuga como punto de encuentro habitual.",
      "id": "fuente-de-arion",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Fuente de Neptuno",
      "cat": "landmark",
      "lat": 49.5925,
      "lng": 17.2524,
      "rating": 4.6,
      "addr": "Dolní náměstí",
      "hours": "24h",
      "note": "La otra gran plaza de Olomouc, preciosa iluminada de noche.",
      "id": "fuente-de-neptuno",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Museo de Historia Natural de Olomouc",
      "cat": "museum",
      "lat": 49.5962833,
      "lng": 17.2570352,
      "rating": 4.5,
      "addr": "Náměstí Republiky 5",
      "hours": "Ma–D 10:00–18:00",
      "note": "Geología, biología y curiosidades locales.",
      "id": "museo-de-historia-natural-de-olomouc",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 250,
      "budgetLabel": "0–250 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Museo de Arte de Olomouc",
      "cat": "museum",
      "lat": 49.5960398,
      "lng": 17.2562577,
      "rating": 4.6,
      "addr": "Denisova 47",
      "hours": "Mi–D 10:00–18:00",
      "note": "Entrada gratis los domingos.",
      "id": "museo-de-arte-de-olomouc",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 250,
      "budgetLabel": "0–250 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Museo Arquidiocesano",
      "cat": "museum",
      "lat": 49.5983094,
      "lng": 17.2616073,
      "rating": 4.7,
      "addr": "Václavské nám. 4",
      "hours": "Mi–D 10:00–18:00",
      "note": "El más importante: frescos románicos, carruajes.",
      "id": "museo-arquidiocesano",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 250,
      "budgetLabel": "0–250 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Pevnost poznání (museo de ciencia)",
      "cat": "museum",
      "lat": 49.5928962,
      "lng": 17.257982,
      "rating": 4.7,
      "addr": "17. listopadu 7",
      "hours": "L–V 9:00–17:00, S–D 10:00–18:00",
      "note": "Fortificación reconvertida, con planetario.",
      "id": "pevnost-poznani-museo-de-ciencia",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 250,
      "budgetLabel": "0–250 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Catedral de San Wenceslao",
      "cat": "church",
      "lat": 49.5977901,
      "lng": 17.2626379,
      "rating": 4.8,
      "addr": "Václavské náměstí",
      "hours": "6:30–17:30 aprox.",
      "note": "Catedral gótica, la más imponente.",
      "id": "catedral-de-san-wenceslao",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Basílica de Svatý Kopeček",
      "cat": "church",
      "lat": 49.629173,
      "lng": 17.338086,
      "rating": 4.7,
      "addr": "Nám. Sadové 1, Svatý Kopeček",
      "hours": "8:30–17:00",
      "note": "Vistas de 200° sobre Olomouc.",
      "id": "basilica-de-svaty-kopecek",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Iglesia de San Miguel",
      "cat": "church",
      "lat": 49.5938981,
      "lng": 17.2541005,
      "rating": 4.8,
      "addr": "Na Hradě",
      "hours": "10:00–19:00",
      "note": "Posiblemente la iglesia más bonita de la ciudad.",
      "id": "iglesia-de-san-miguel",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Iglesia de San Mauricio",
      "cat": "church",
      "lat": 49.5951618,
      "lng": 17.2512985,
      "rating": 4.8,
      "addr": "8. května 15",
      "hours": "7:00–17:00",
      "note": "Sube la torre-campanario, las mejores vistas.",
      "id": "iglesia-de-san-mauricio",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Iglesia Roja (Červený kostel)",
      "cat": "church",
      "lat": 49.5934797,
      "lng": 17.2472531,
      "rating": 4.7,
      "addr": "Bezručova 3",
      "hours": "L–V 8:30–19:00",
      "note": "Reconvertida en espacio cultural con cafetería.",
      "id": "iglesia-roja-cerveny-kostel",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Huellas de la iglesia medieval",
      "cat": "secret",
      "lat": 49.59195,
      "lng": 17.25178,
      "rating": null,
      "addr": "Dolní náměstí (pavimento)",
      "hours": "24h",
      "note": "El contorno de 3 iglesias superpuestas (s.XII-XVI) trazado en los adoquines, hallado en 2011. Casi nadie se fija.",
      "id": "huellas-de-la-iglesia-medieval",
      "scope": "city",
      "points": 25,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Calle de los Xenomorfos",
      "cat": "secret",
      "lat": 49.5908978,
      "lng": 17.2526413,
      "rating": 4.9,
      "addr": "Šemberova",
      "hours": "24h",
      "note": "Esculturas de alien de acero de Jan Dostál escondidas en una calle residencial.",
      "id": "calle-de-los-xenomorfos",
      "scope": "city",
      "points": 25,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Masné krámy y sus bares ocultos",
      "cat": "secret",
      "lat": 49.5919919,
      "lng": 17.2517703,
      "rating": 4.4,
      "addr": "Dolní nám. 25",
      "hours": "Variable según local",
      "note": "Pasaje histórico con varios locales escondidos, entre ellos Republica y Blaylock. Un único descubrimiento evita sumar tres veces por la misma ubicación.",
      "id": "masne-kramy-antiguo-mercado-de-carne",
      "tags": [
        "secreto",
        "bares",
        "pasaje",
        "centro"
      ],
      "points": 25,
      "scope": "city",
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "event",
      "statusText": "Solo con evento / consulta",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Telegraph Gallery",
      "cat": "secret",
      "lat": 49.5906174,
      "lng": 17.2763106,
      "rating": 4.7,
      "addr": "Jungmannova 3, Hodolany",
      "hours": "Ma–D 9:00–19:00",
      "note": "Galería de arte + café + coworking, entrada gratis, poco turística.",
      "id": "telegraph-gallery",
      "scope": "city",
      "points": 25,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Vinný šenk U Zlatého beránka",
      "cat": "secret",
      "lat": 49.5955254,
      "lng": 17.2553662,
      "rating": 4.7,
      "addr": "Univerzitní nám. 2",
      "hours": "L–S 16:00–00:00",
      "note": "Bodega escondida con cata de vino y queso a precio de estudiante.",
      "id": "vinny-senk-u-zlateho-beranka",
      "scope": "city",
      "points": 25,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Letní kino Hoblina",
      "cat": "secret",
      "lat": 49.5978234,
      "lng": 17.2599576,
      "rating": 4.4,
      "addr": "Pekárná 9/26",
      "hours": "L–D 12:00/14:00–22:00",
      "note": "Cine de verano con jardín, hoguera y hamacas — muy local, poco turista.",
      "id": "letni-kino-hoblina",
      "scope": "city",
      "points": 25,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Monasterio de Hradisko",
      "cat": "secret",
      "lat": 49.6056673,
      "lng": 17.2651118,
      "rating": 4.7,
      "addr": "Sušilovo nám. 4/4",
      "hours": "7:30–15:30 aprox.",
      "note": "Antiguo monasterio benedictino, hoy hospital militar — fachada barroca impresionante.",
      "id": "monasterio-de-hradisko",
      "scope": "city",
      "points": 25,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Búnker antiatómico (Institut Paměti národa)",
      "cat": "secret",
      "lat": 49.5935899,
      "lng": 17.2554862,
      "rating": 4.5,
      "addr": "Bezručovy sady",
      "hours": "Sáb 13:00–17:00",
      "note": "Refugio nuclear de los 50 escondido bajo el parque, casi invisible desde fuera.",
      "id": "bunker-antiatomico-institut-pameti-naroda",
      "scope": "city",
      "points": 25,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Biblioteca Municipal de Olomouc",
      "cat": "secret",
      "lat": 49.596243,
      "lng": 17.258282,
      "rating": 4.7,
      "addr": "Nám. Republiky 856/1",
      "hours": "L,Ma,Ju,V 8:00–18:00, S 8:00–12:00",
      "note": "Patios interiores escondidos, edificio neoclásico precioso.",
      "id": "biblioteca-municipal-de-olomouc",
      "scope": "city",
      "points": 25,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Sayes Bar",
      "cat": "secret",
      "lat": 49.5968871,
      "lng": 17.2608268,
      "rating": 5,
      "addr": "1. máje 32",
      "hours": "Ma–D 17:00–1:00/2:00",
      "note": "Cócteles de autor fuera del circuito habitual, justo frente al Black Stuff.",
      "id": "sayes-bar",
      "scope": "city",
      "points": 25,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Aquapark Olomouc",
      "cat": "activity",
      "lat": 49.5743011,
      "lng": 17.2230485,
      "rating": 4.2,
      "addr": "Kafkova 526/21",
      "hours": "9:00–21:00",
      "note": "Toboganes, piscina exterior y zona wellness.",
      "id": "aquapark-olomouc",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 500,
      "budgetLabel": "0–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Zoo Olomouc",
      "cat": "activity",
      "lat": 49.6334455,
      "lng": 17.3433672,
      "rating": 4.4,
      "addr": "Darwinova 222/29, Svatý Kopeček",
      "hours": "9:00–18:00",
      "note": "Uno de los mejores zoos de Chequia, combínalo con la basílica.",
      "id": "zoo-olomouc",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 500,
      "budgetLabel": "0–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Lanový park Veverák",
      "cat": "activity",
      "lat": 49.6339668,
      "lng": 17.3457354,
      "rating": 4.7,
      "addr": "Svatý Kopeček (junto al ZOO)",
      "hours": "9:00–18:00",
      "note": "Parque de cuerdas y tirolinas, 3 rutas de dificultad.",
      "id": "lanovy-park-veverak",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 500,
      "budgetLabel": "0–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Ruta ciclista Olomouc – Litovelské Pomoraví",
      "cat": "activity",
      "lat": 49.573,
      "lng": 17.2617,
      "rating": 4.8,
      "addr": "Ribera del río Morava",
      "hours": "24h",
      "note": "Ruta llana junto al Morava hacia Horka, Sluňákov y Litovel. Es una de las mejores formas de integrar naturaleza en la vida semanal.",
      "id": "cyklotrasa-podel-moravy",
      "tags": [
        "bici",
        "naturaleza",
        "litovel",
        "río",
        "ruta"
      ],
      "points": 20,
      "scope": "city",
      "budgetMin": 0,
      "budgetMax": 250,
      "budgetLabel": "0–250 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Vodácký svět (alquiler de kayak/paddleboard)",
      "cat": "activity",
      "lat": 49.5649,
      "lng": 17.2367,
      "rating": 4.6,
      "addr": "Kyselovská 80/57",
      "hours": "L,Ma,Ju,V 9:00–12:00, 14:00–18:00",
      "note": "Alquilan kayaks y paddleboards para bajar el Morava; también enseñan la vuelta de esquimal.",
      "id": "vodacky-svet-alquiler-de-kayak-paddleboard",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 500,
      "budgetLabel": "0–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Pivovar TVARG (Velká Bystřice)",
      "cat": "activity",
      "lat": 49.5946,
      "lng": 17.3581,
      "rating": 4.5,
      "addr": "Velká Bystřice (~15 min en coche)",
      "hours": "11:00–20:00/21:00/23:00",
      "note": "Cervecería + fábrica de tvarůžky (el queso típico de la región); hacen visitas guiadas con cata.",
      "id": "pivovar-tvarg-velka-bystrice",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 500,
      "budgetLabel": "0–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Jardín Botánico – Rosaleda",
      "cat": "activity",
      "lat": 49.5922031,
      "lng": 17.2613187,
      "rating": 4.7,
      "addr": "17. listopadu, junto a Bezručovy sady",
      "hours": "9:00–18:00",
      "note": "Un oasis floral dentro de la propia ciudad — espectacular en junio con las rosas en flor.",
      "id": "jardin-botanico-rosaleda",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 500,
      "budgetLabel": "0–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Recinto ferial Flora Olomouc",
      "cat": "activity",
      "lat": 49.5882225,
      "lng": 17.2456322,
      "rating": 4.4,
      "addr": "Wolkerova 37/17",
      "hours": "Según exposición",
      "note": "Parque + pabellones de exposiciones (flores, coches clásicos, gatos...); consulta el calendario de ferias.",
      "id": "recinto-ferial-flora-olomouc",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 500,
      "budgetLabel": "0–500 CZK",
      "statusType": "event",
      "statusText": "Solo con evento / consulta",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Lago Chomoutov",
      "cat": "activity",
      "lat": 49.6541638,
      "lng": 17.2399239,
      "rating": 4.6,
      "addr": "Chomoutov (~15 min en bici desde el centro)",
      "hours": "24h",
      "note": "Lago tranquilo rodeado de naturaleza, ideal para una tarde de picnic o paseo en bici.",
      "id": "lago-chomoutov",
      "scope": "city",
      "points": 15,
      "budgetMin": 0,
      "budgetMax": 500,
      "budgetLabel": "0–500 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Casa de la Naturaleza – Litovelské Pomoraví",
      "cat": "activity",
      "lat": 49.641438,
      "lng": 17.1998823,
      "rating": 4.6,
      "addr": "Skrbeňská 669, Horka nad Moravou (~20 min en coche/bici)",
      "hours": "9:00–17:00/18:00",
      "note": "Puerta de entrada a bosques de ribera, humedales y rutas ciclistas. Combínala con Sluňákov y Poděbrady.",
      "tags": [
        "naturaleza",
        "bici",
        "humedales",
        "sluňákov"
      ],
      "points": 20,
      "id": "casa-de-la-naturaleza-litovelske-pomoravi",
      "scope": "city",
      "budgetMin": 0,
      "budgetMax": 500,
      "budgetLabel": "0–500 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Lago Poděbrady",
      "cat": "activity",
      "lat": 49.625313,
      "lng": 17.226923,
      "rating": 4.6,
      "addr": "Horka nad Moravou, ~5 km de Olomouc",
      "hours": "Acceso libre; baño según temporada y calidad del agua",
      "note": "Lago natural para baño, picnic y bici. Muy buena microescapada desde ambas residencias y puerta de entrada a Litovelské Pomoraví.",
      "tags": [
        "naturaleza",
        "baño",
        "bici",
        "picnic",
        "verano"
      ],
      "radius": 600,
      "points": 20,
      "id": "lago-podebrady",
      "scope": "city",
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "seasonal",
      "statusText": "Estacional",
      "lastVerified": "27/07/2026"
    },
    {
      "name": "Mirador de Svatý Kopeček",
      "cat": "viewpoint",
      "lat": 49.628897,
      "lng": 17.3374461,
      "rating": 4.9,
      "addr": "Nám. Sadové 2, Svatý Kopeček",
      "hours": "24h",
      "note": "El mejor atardecer cerca de Olomouc.",
      "id": "mirador-de-svaty-kopecek",
      "scope": "city",
      "points": 20,
      "budgetMin": 0,
      "budgetMax": 350,
      "budgetLabel": "0–350 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Torre panorámica del ZOO Olomouc",
      "cat": "viewpoint",
      "lat": 49.6341237,
      "lng": 17.3403902,
      "rating": 4.6,
      "addr": "Svatý Kopeček",
      "hours": "L–V 8:00–20:00",
      "note": "Entrada libre a la torre.",
      "id": "torre-panoramica-del-zoo-olomouc",
      "scope": "city",
      "points": 20,
      "budgetMin": 0,
      "budgetMax": 350,
      "budgetLabel": "0–350 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Velký Kosíř (mirador y senderismo)",
      "cat": "viewpoint",
      "lat": 49.5483398,
      "lng": 17.0617409,
      "rating": 4.6,
      "addr": "Slatinky-Slatinice (~25 min en coche)",
      "hours": "24h (torre con horario propio)",
      "note": "El 'monte' más alto de la llanura de Haná — subida fácil en familia, con torre-mirador y zona de barbacoa.",
      "id": "velky-kosir-mirador-y-senderismo",
      "scope": "trip",
      "points": 20,
      "budgetMin": 0,
      "budgetMax": 350,
      "budgetLabel": "0–350 CZK",
      "statusType": "always",
      "statusText": "Abierto 24 h",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 1100
    },
    {
      "name": "Castillo de Bouzov",
      "cat": "daytrip",
      "lat": 49.7049411,
      "lng": 16.8895083,
      "rating": 4.8,
      "addr": "Bouzov 8 (~40 min en coche)",
      "hours": "9:00–16:00",
      "note": "El castillo de cuento más famoso de Moravia.",
      "id": "castillo-de-bouzov",
      "scope": "trip",
      "points": 30,
      "budgetMin": 300,
      "budgetMax": 1000,
      "budgetLabel": "300–1.000 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 1100
    },
    {
      "name": "Cuevas de Javoříčko",
      "cat": "daytrip",
      "lat": 49.6703174,
      "lng": 16.9139189,
      "rating": 4.8,
      "addr": "Javoříčko (~35 min en coche)",
      "hours": "Ma–D 9:00–16:00",
      "note": "Combínalas con Bouzov — 7°C todo el año.",
      "id": "cuevas-de-javoricko",
      "scope": "trip",
      "points": 30,
      "budgetMin": 300,
      "budgetMax": 1000,
      "budgetLabel": "300–1.000 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 1100
    },
    {
      "name": "Kroměříž: palacio y jardines UNESCO",
      "cat": "daytrip",
      "lat": 49.3004779,
      "lng": 17.3935276,
      "rating": 4.7,
      "addr": "Kroměříž (~1h en coche/tren)",
      "hours": "Ma–D 8:30–18:00",
      "note": "Escapada cultural completa: palacio arzobispal, jardines y casco histórico. Mejor como una sola misión, no como dos pines contiguos.",
      "id": "palacio-arzobispal-de-kromeriz-unesco",
      "tags": [
        "unesco",
        "tren",
        "jardines",
        "palacio"
      ],
      "points": 30,
      "scope": "trip",
      "budgetMin": 300,
      "budgetMax": 1000,
      "budgetLabel": "300–1.000 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 1100
    },
    {
      "name": "Museo del queso Olomoucké tvarůžky (Loštice)",
      "cat": "daytrip",
      "lat": 49.7456076,
      "lng": 16.9278082,
      "rating": 4.8,
      "addr": "Palackého 56, Loštice (~45 min en coche)",
      "hours": "9:00–18:00",
      "note": "El queso típico de la región.",
      "id": "museo-del-queso-olomoucke-tvaruzky-lostice",
      "scope": "trip",
      "points": 30,
      "budgetMin": 300,
      "budgetMax": 1000,
      "budgetLabel": "300–1.000 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 1100
    },
    {
      "name": "Kouty nad Desnou + Dlouhé Stráně",
      "cat": "daytrip",
      "lat": 50.0733,
      "lng": 17.1917,
      "rating": null,
      "addr": "Kouty nad Desnou (~50 min en coche o tren)",
      "hours": "Todo el año; remontes y visitas según temporada",
      "note": "Una de las mejores escapadas sin coche: tren hasta Kouty, montaña, bici o esquí y acceso al entorno de la central de Dlouhé Stráně.",
      "id": "kouty-nad-desnou",
      "tags": [
        "tren",
        "montaña",
        "senderismo",
        "esquí",
        "sin coche"
      ],
      "points": 35,
      "scope": "trip",
      "budgetMin": 300,
      "budgetMax": 900,
      "budgetLabel": "300–900 CZK",
      "statusType": "seasonal",
      "statusText": "Estacional",
      "lastVerified": "27/07/2026",
      "radius": 1100
    },
    {
      "name": "Ramzová – Šerák – Keprník",
      "cat": "daytrip",
      "lat": 50.1934,
      "lng": 17.1508,
      "rating": null,
      "addr": "Ramzová (~1h20 en coche)",
      "hours": "Todo el año; telesilla según temporada",
      "note": "Gran ruta de montaña accesible en tren. Se puede subir en telesilla a Šerák o enlazar una ruta exigente por Keprník.",
      "id": "ramzova-serak-bonera",
      "tags": [
        "tren",
        "senderismo",
        "montaña",
        "jeseniky",
        "telesilla"
      ],
      "points": 40,
      "scope": "trip",
      "budgetMin": 250,
      "budgetMax": 750,
      "budgetLabel": "250–750 CZK",
      "statusType": "seasonal",
      "statusText": "Estacional",
      "lastVerified": "27/07/2026",
      "radius": 1100
    },
    {
      "name": "Dolní Morava + Sky Bridge 721",
      "cat": "daytrip",
      "lat": 50.1275,
      "lng": 16.8378,
      "rating": null,
      "addr": "Dolní Morava (~1h30 en coche)",
      "hours": "Todo el año; consultar instalaciones",
      "note": "Destino de aventura con montaña, puente colgante y actividades. Merece más como escapada completa que como simple estación de esquí.",
      "id": "dolni-morava-kralicky-sneznik",
      "tags": [
        "montaña",
        "aventura",
        "sky bridge",
        "coche"
      ],
      "points": 40,
      "scope": "trip",
      "budgetMin": 900,
      "budgetMax": 1800,
      "budgetLabel": "900–1.800 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 1100
    },
    {
      "name": "Cuevas de Mladeč",
      "cat": "daytrip",
      "lat": 49.7065924,
      "lng": 17.0158358,
      "rating": 4.6,
      "addr": "Mladeč 84 (~35 min en coche)",
      "hours": "Ma–D 9:00–16:30",
      "note": "Combínalas con las de Javoříčko en la misma ruta — más cortas pero con hallazgos prehistóricos importantes.",
      "id": "cuevas-de-mladec",
      "scope": "trip",
      "points": 30,
      "budgetMin": 300,
      "budgetMax": 1000,
      "budgetLabel": "300–1.000 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 1100
    },
    {
      "name": "Hranice: abismo y cuevas de Zbrašov",
      "cat": "daytrip",
      "lat": 49.532,
      "lng": 17.7508,
      "rating": 4.8,
      "addr": "Teplice nad Bečvou / Hranice",
      "hours": "Cuevas con horario; abismo accesible todo el año",
      "note": "Escapada muy recomendable en tren: el abismo inundado más profundo conocido y las cuevas termales de Zbrašov en la misma zona.",
      "tags": [
        "tren",
        "cuevas",
        "naturaleza",
        "hranice"
      ],
      "radius": 900,
      "points": 35,
      "id": "hranice-abismo-y-cuevas-de-zbrasov",
      "scope": "trip",
      "budgetMin": 300,
      "budgetMax": 1000,
      "budgetLabel": "300–1.000 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026"
    },
    {
      "name": "Helfštýn + Lipník nad Bečvou",
      "cat": "daytrip",
      "lat": 49.5181,
      "lng": 17.6286,
      "rating": 4.7,
      "addr": "Castillo de Helfštýn",
      "hours": "Horario estacional del castillo",
      "note": "Castillo enorme sobre el valle de la Puerta de Moravia. Se puede combinar con Lipník y una caminata desde el tren.",
      "tags": [
        "tren",
        "castillo",
        "senderismo",
        "lipník"
      ],
      "radius": 900,
      "points": 35,
      "id": "helfstyn-lipnik-nad-becvou",
      "scope": "trip",
      "budgetMin": 300,
      "budgetMax": 1000,
      "budgetLabel": "300–1.000 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026"
    },
    {
      "name": "Karlova Studánka – Bílá Opava – Praděd",
      "cat": "daytrip",
      "lat": 50.059616,
      "lng": 17.392736,
      "rating": 4.9,
      "addr": "Jeseníky",
      "hours": "Ruta de montaña; evitar hielo y crecidas",
      "note": "Probablemente la excursión natural más espectacular de la zona: cascadas y pasarelas de Bílá Opava, balneario de Karlova Studánka y opción de continuar al Praděd.",
      "tags": [
        "jeseniky",
        "senderismo",
        "cascadas",
        "montaña",
        "exigente"
      ],
      "radius": 1500,
      "points": 45,
      "id": "karlova-studanka-bila-opava-praded",
      "scope": "trip",
      "budgetMin": 250,
      "budgetMax": 650,
      "budgetLabel": "250–650 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026"
    },
    {
      "name": "Rejvíz y Gran Lago de Musgo",
      "cat": "daytrip",
      "lat": 50.219754,
      "lng": 17.286773,
      "rating": 4.8,
      "addr": "Rejvíz, Jeseníky",
      "hours": "Sendero con horario/tarifa estacional en el acceso al lago",
      "note": "Bosque, turberas y pasarelas de madera en uno de los paisajes más singulares de Jeseníky. Ideal en otoño y primavera.",
      "tags": [
        "jeseniky",
        "turbera",
        "bosque",
        "otoño",
        "senderismo"
      ],
      "radius": 900,
      "points": 40,
      "id": "rejviz-y-gran-lago-de-musgo",
      "scope": "trip",
      "budgetMin": 300,
      "budgetMax": 1000,
      "budgetLabel": "300–1.000 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026"
    },
    {
      "name": "Velké Losiny: termas, papel y castillo",
      "cat": "daytrip",
      "lat": 50.021683,
      "lng": 17.078788,
      "rating": 4.7,
      "addr": "Velké Losiny",
      "hours": "Consultar termas, castillo y papelera",
      "note": "Escapada de día completo combinando termas, castillo renacentista y la histórica fábrica de papel. Accesible en tren con planificación.",
      "tags": [
        "tren",
        "termas",
        "castillo",
        "papel",
        "invierno"
      ],
      "radius": 1000,
      "points": 35,
      "id": "velke-losiny-termas-papel-y-castillo",
      "scope": "trip",
      "budgetMin": 300,
      "budgetMax": 1000,
      "budgetLabel": "300–1.000 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026"
    },
    {
      "name": "Šternberk: castillo y museo del tiempo",
      "cat": "town",
      "lat": 49.733056,
      "lng": 17.301858,
      "rating": 4.6,
      "addr": "Šternberk (~25 min en coche/tren)",
      "hours": "9:00–16:00 (cerrado lun)",
      "note": "Escapada fácil en tren: castillo, casco urbano y curioso museo del tiempo en una sola jornada.",
      "id": "castillo-de-sternberk",
      "tags": [
        "tren",
        "castillo",
        "pueblo",
        "fácil"
      ],
      "points": 25,
      "scope": "trip",
      "budgetMin": 200,
      "budgetMax": 650,
      "budgetLabel": "200–650 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 1100
    },
    {
      "name": "Litovel y la “Venecia de Haná”",
      "cat": "town",
      "lat": 49.7016015,
      "lng": 17.0750529,
      "rating": 4.7,
      "addr": "Nám. Přemysla Otakara, Litovel (~30 min en coche)",
      "hours": "10:00–16:00",
      "note": "Pueblo pequeño atravesado por brazos del Morava. Se llega en tren o en bici por Litovelské Pomoraví.",
      "id": "torre-del-ayuntamiento-de-litovel",
      "tags": [
        "tren",
        "bici",
        "río",
        "pueblo"
      ],
      "points": 25,
      "scope": "trip",
      "budgetMin": 200,
      "budgetMax": 650,
      "budgetLabel": "200–650 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 1100
    },
    {
      "name": "Centro de Información Turística de Olomouc",
      "cat": "freetour",
      "lat": 49.5940537,
      "lng": 17.2514875,
      "rating": 4.5,
      "addr": "Horní nám. 583/1",
      "hours": "L–S 9:00–19:00, D 9:00–17:00",
      "note": "Punto de salida de tours guiados; venden la Olomouc Region Card.",
      "id": "centro-de-informacion-turistica-de-olomouc",
      "scope": "city",
      "points": 5,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "tags": [],
      "radius": 250
    },
    {
      "name": "Legends Gym Olomouc",
      "cat": "gym",
      "lat": 49.6000475,
      "lng": 17.2674527,
      "rating": 4.8,
      "addr": "Sokolovská 80/4",
      "hours": "L–V 6:00–21:00, S–D 8:00–20:00",
      "note": "Gimnasio completo al este de la ciudad; mantenido como alternativa de equipamiento amplio.",
      "tags": [
        "gimnasio",
        "pesas",
        "deporte"
      ],
      "id": "legends-gym-olomouc",
      "scope": "city",
      "points": 2,
      "budgetMin": 120,
      "budgetMax": 300,
      "budgetLabel": "120–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Eurogym Fitness",
      "cat": "gym",
      "lat": 49.5892524,
      "lng": 17.2338027,
      "rating": 4.5,
      "addr": "Stupkova 18/952",
      "hours": "L–V 6:00–00:00, S–D 7:00–22:00",
      "note": "Opción práctica y económica para estudiantes al oeste del centro; acepta MultiSport cuando sea aplicable.",
      "tags": [
        "gimnasio",
        "barato",
        "multisport",
        "neredin"
      ],
      "id": "eurogym-fitness",
      "scope": "city",
      "points": 2,
      "budgetMin": 120,
      "budgetMax": 300,
      "budgetLabel": "120–300 CZK",
      "statusType": "community",
      "statusText": "Revisa antes de ir",
      "lastVerified": "27/07/2026",
      "radius": 250
    },
    {
      "name": "Facultad de Ciencias de la Salud",
      "cat": "faculty",
      "lat": 49.5862796,
      "lng": 17.2366108,
      "rating": null,
      "addr": "Hněvotínská 976/3",
      "hours": "Horario académico",
      "note": "Comparte el campus sanitario con Medicina. Comprueba el aula exacta en STAG antes de salir.",
      "tags": [
        "facultad",
        "salud",
        "enfermeria",
        "campus sanitario",
        "upol"
      ],
      "lastVerified": "27/07/2026",
      "radius": 220,
      "officialUrl": "https://www.fzv.upol.cz/en/",
      "id": "facultad-de-ciencias-de-la-salud",
      "scope": "city",
      "points": 1,
      "budgetMin": 0,
      "budgetMax": 100,
      "budgetLabel": "0–100 CZK",
      "statusType": "verify",
      "statusText": "Horario por confirmar"
    }
  ],
  "missions": [
    {
      "id": "first-days",
      "name": "Primeros días",
      "icon": "🧳",
      "bonus": 10,
      "description": "Aprende a moverte y localiza los servicios imprescindibles.",
      "placeNames": [
        "Centro Erasmus UPOL (Welcome Office + Mobility + ESN)",
        "Zbrojnice – biblioteca 24h + oficina ISIC",
        "DPMO – abonos y tarjetas de transporte",
        "Estación de tren de Olomouc"
      ]
    },
    {
      "id": "university-life",
      "name": "Vida universitaria",
      "icon": "🎓",
      "bonus": 15,
      "description": "Completa ocho servicios, facultades, comedores o espacios universitarios.",
      "categories": [
        "canteen",
        "faculty",
        "dorm",
        "essential"
      ],
      "target": 8
    },
    {
      "id": "baroque",
      "name": "Olomouc barroca",
      "icon": "🏛️",
      "bonus": 25,
      "description": "Descubre el gran patrimonio barroco de la ciudad.",
      "placeNames": [
        "Columna de la Santísima Trinidad",
        "Fuente de Hércules",
        "Fuente de Neptuno",
        "Iglesia de San Miguel",
        "Iglesia de San Mauricio"
      ]
    },
    {
      "id": "hidden",
      "name": "Olomouc secreta",
      "icon": "🗝️",
      "bonus": 30,
      "description": "Encuentra cinco lugares escondidos o poco conocidos.",
      "categories": [
        "secret"
      ],
      "target": 5
    },
    {
      "id": "wild-city",
      "name": "Olomouc natural",
      "icon": "🌿",
      "bonus": 35,
      "description": "Integra río, lagos, bici y bosques en la vida cotidiana.",
      "placeNames": [
        "Lago Poděbrady",
        "Ruta ciclista Olomouc – Litovelské Pomoraví",
        "Casa de la Naturaleza – Litovelské Pomoraví",
        "Lago Chomoutov",
        "Mirador de Svatý Kopeček"
      ],
      "target": 4
    },
    {
      "id": "svaty",
      "name": "Día en Svatý Kopeček",
      "icon": "🌄",
      "bonus": 25,
      "description": "Completa una jornada de basílica, vistas y actividades.",
      "placeNames": [
        "Basílica de Svatý Kopeček",
        "Mirador de Svatý Kopeček",
        "Zoo Olomouc",
        "Torre panorámica del ZOO Olomouc"
      ]
    },
    {
      "id": "jeseniky",
      "name": "Jeseníky natural",
      "icon": "🥾",
      "bonus": 55,
      "description": "Completa tres grandes salidas de montaña.",
      "placeNames": [
        "Karlova Studánka – Bílá Opava – Praděd",
        "Ramzová – Šerák – Keprník",
        "Rejvíz y Gran Lago de Musgo",
        "Kouty nad Desnou + Dlouhé Stráně"
      ],
      "target": 3
    },
    {
      "id": "train-escape",
      "name": "Escapadas en tren",
      "icon": "🚆",
      "bonus": 45,
      "description": "Demuestra que no hace falta coche para vivir aventuras.",
      "placeNames": [
        "Hranice: abismo y cuevas de Zbrašov",
        "Šternberk: castillo y museo del tiempo",
        "Litovel y la “Venecia de Haná”",
        "Ramzová – Šerák – Keprník",
        "Velké Losiny: termas, papel y castillo",
        "Kouty nad Desnou + Dlouhé Stráně"
      ],
      "target": 3
    },
    {
      "id": "moravia",
      "name": "Explora Moravia",
      "icon": "🧭",
      "bonus": 50,
      "description": "Haz cinco escapadas distintas fuera de Olomouc.",
      "scopes": [
        "trip"
      ],
      "target": 5
    }
  ],
  "routes": [
    {
      "id": "connect-campuses",
      "name": "Conecta Neředín y Envelopa",
      "icon": "🚋",
      "type": "urban",
      "duration": "2–3 h",
      "budgetMin": 25,
      "budgetMax": 200,
      "budget": "25–200 CZK",
      "difficulty": "Fácil",
      "transport": "Tranvía 2/7 + paseo",
      "best": "Primeros días",
      "description": "Aprende el trayecto entre las dos residencias y los servicios que quedan entre ambas.",
      "placeNames": [
        "Campus Neředín (residencias Erasmus)",
        "Parada Neředín, krematorium",
        "Campus Envelopa (residencias Erasmus)",
        "Menza 17. listopadu",
        "Estación de tren de Olomouc"
      ]
    },
    {
      "id": "first-day",
      "name": "Primer día práctico",
      "icon": "🧳",
      "type": "urban",
      "duration": "3–4 h",
      "budgetMin": 25,
      "budgetMax": 400,
      "budget": "25–400 CZK",
      "difficulty": "Fácil",
      "transport": "Tranvía + a pie",
      "best": "Al llegar",
      "description": "Tarjeta, transporte, comida y orientación sin perder el día.",
      "placeNames": [
        "Centro Erasmus UPOL (Welcome Office + Mobility + ESN)",
        "Zbrojnice – biblioteca 24h + oficina ISIC",
        "DPMO – abonos y tarjetas de transporte",
        "Menza 17. listopadu",
        "UPoint – información y tienda de la universidad"
      ]
    },
    {
      "id": "historic-center",
      "name": "Centro histórico esencial",
      "icon": "🏛️",
      "type": "urban",
      "duration": "2–3 h",
      "budgetMin": 0,
      "budgetMax": 250,
      "budget": "0–250 CZK",
      "difficulty": "Fácil",
      "transport": "A pie",
      "best": "Cualquier tarde",
      "description": "La primera ruta para entender Olomouc y localizar sus plazas principales.",
      "placeNames": [
        "Columna de la Santísima Trinidad",
        "Reloj Astronómico de Olomouc",
        "Fuente de Hércules",
        "Fuente de Neptuno",
        "Iglesia de San Mauricio"
      ]
    },
    {
      "id": "hidden-olomouc",
      "name": "Olomouc secreta",
      "icon": "🗝️",
      "type": "urban",
      "duration": "3 h",
      "budgetMin": 0,
      "budgetMax": 350,
      "budget": "0–350 CZK",
      "difficulty": "Fácil",
      "transport": "A pie",
      "best": "Tarde y noche",
      "description": "Patios, pasajes y rincones que no parecen una ruta turística convencional.",
      "placeNames": [
        "Huellas de la iglesia medieval",
        "Calle de los Xenomorfos",
        "Masné krámy y sus bares ocultos",
        "Búnker antiatómico (Institut Paměti národa)",
        "Letní kino Hoblina"
      ]
    },
    {
      "id": "svaty-day",
      "name": "Día en Svatý Kopeček",
      "icon": "🌄",
      "type": "nature",
      "duration": "5–7 h",
      "budgetMin": 50,
      "budgetMax": 650,
      "budget": "50–650 CZK",
      "difficulty": "Fácil–media",
      "transport": "Bus 11 / bici",
      "best": "Día despejado",
      "description": "Vistas, basílica, zoo y parque de cuerdas en una misma zona.",
      "placeNames": [
        "Basílica de Svatý Kopeček",
        "Mirador de Svatý Kopeček",
        "Zoo Olomouc",
        "Torre panorámica del ZOO Olomouc",
        "Lanový park Veverák"
      ]
    },
    {
      "id": "podebrady-bike",
      "name": "Tarde en Poděbrady",
      "icon": "🚲",
      "type": "nature",
      "duration": "3–5 h",
      "budgetMin": 0,
      "budgetMax": 250,
      "budget": "0–250 CZK",
      "difficulty": "Fácil",
      "transport": "Bicicleta",
      "best": "Sol y calor",
      "description": "La escapada natural más sencilla: pedalear, bañarse, hacer picnic y volver antes de cenar.",
      "placeNames": [
        "Ruta ciclista Olomouc – Litovelské Pomoraví",
        "Lago Poděbrady",
        "Casa de la Naturaleza – Litovelské Pomoraví"
      ]
    },
    {
      "id": "litovel-bike",
      "name": "Olomouc–Litovel en bici",
      "icon": "🌿",
      "type": "nature",
      "duration": "6–8 h",
      "budgetMin": 100,
      "budgetMax": 450,
      "budget": "100–450 CZK",
      "difficulty": "Media",
      "transport": "Bici + tren opcional",
      "best": "Primavera u otoño",
      "description": "Bosques de ribera, pueblos y posibilidad de volver en tren.",
      "placeNames": [
        "Ruta ciclista Olomouc – Litovelské Pomoraví",
        "Casa de la Naturaleza – Litovelské Pomoraví",
        "Litovel y la “Venecia de Haná”"
      ]
    },
    {
      "id": "bouzov-caves",
      "name": "Bouzov y Javoříčko",
      "icon": "🏰",
      "type": "trip",
      "duration": "Día completo",
      "budgetMin": 500,
      "budgetMax": 1000,
      "budget": "500–1.000 CZK",
      "difficulty": "Fácil",
      "transport": "Coche compartido / bus",
      "best": "Abril–octubre",
      "description": "Castillo de cuento y cuevas en una de las excursiones clásicas desde Olomouc.",
      "placeNames": [
        "Castillo de Bouzov",
        "Cuevas de Javoříčko"
      ]
    },
    {
      "id": "hranice",
      "name": "Hranice: abismo y cuevas",
      "icon": "🕳️",
      "type": "trip",
      "duration": "Día completo",
      "budgetMin": 300,
      "budgetMax": 750,
      "budget": "300–750 CZK",
      "difficulty": "Fácil–media",
      "transport": "Tren",
      "best": "Todo el año",
      "description": "Una escapada geológica fácil de organizar sin coche.",
      "placeNames": [
        "Hranice: abismo y cuevas de Zbrašov"
      ]
    },
    {
      "id": "praded",
      "name": "Bílá Opava y Praděd",
      "icon": "🥾",
      "type": "mountain",
      "duration": "Día completo",
      "budgetMin": 350,
      "budgetMax": 800,
      "budget": "350–800 CZK",
      "difficulty": "Media–alta",
      "transport": "Coche / bus coordinado",
      "best": "Junio–octubre",
      "description": "La gran ruta de cascadas y montaña de Jeseníky.",
      "placeNames": [
        "Karlova Studánka – Bílá Opava – Praděd"
      ]
    },
    {
      "id": "ramzova",
      "name": "Ramzová–Šerák–Keprník",
      "icon": "⛰️",
      "type": "mountain",
      "duration": "Día completo",
      "budgetMin": 300,
      "budgetMax": 850,
      "budget": "300–850 CZK",
      "difficulty": "Media–alta",
      "transport": "Tren",
      "best": "Mayo–octubre",
      "description": "Cresta de montaña accesible en tren, con opción de telesilla.",
      "placeNames": [
        "Ramzová – Šerák – Keprník"
      ]
    },
    {
      "id": "winter",
      "name": "Invierno en Kouty",
      "icon": "🎿",
      "type": "mountain",
      "duration": "Día completo",
      "budgetMin": 800,
      "budgetMax": 1800,
      "budget": "800–1.800 CZK",
      "difficulty": "Variable",
      "transport": "Tren",
      "best": "Con nieve",
      "description": "Esquí o montaña invernal con estación ferroviaria junto al resort.",
      "placeNames": [
        "Kouty nad Desnou + Dlouhé Stráně"
      ]
    }
  ],
  "events": [
    {
      "id": "pre-arrival",
      "title": "Orientación online previa",
      "start": "2026-09-07T10:00:00",
      "end": "2026-09-07T12:00:00",
      "type": "official",
      "location": "Online",
      "description": "Sesión previa para estudiantes registrados. La invitación y hora exacta llegan por correo de UPOL.",
      "source": "UPOL"
    },
    {
      "id": "dorm-arrival",
      "title": "Llegada recomendada a residencias",
      "start": "2026-09-11T08:00:00",
      "end": "2026-09-13T22:00:00",
      "type": "official",
      "location": "Neředín y Envelopa",
      "description": "Ventana oficial recomendada para instalarse antes de la Orientation Week.",
      "source": "UPOL"
    },
    {
      "id": "orientation-week",
      "title": "Orientation Week",
      "start": "2026-09-14T08:00:00",
      "end": "2026-09-18T22:00:00",
      "type": "official",
      "location": "Palacký University Olomouc",
      "description": "Programa de bienvenida y actividades para Erasmus+ y estudiantes de intercambio. El horario detallado se enviará por correo.",
      "source": "UPOL"
    },
    {
      "id": "classes-start",
      "title": "Inicio general de clases",
      "start": "2026-09-21T08:00:00",
      "end": "2026-09-21T18:00:00",
      "type": "official",
      "location": "Facultades UPOL",
      "description": "Inicio general del semestre de invierno; Medicina y Ciencias de la Salud pueden tener fechas específicas.",
      "source": "UPOL"
    },
    {
      "id": "classes-end",
      "title": "Fin general de clases",
      "start": "2026-12-18T08:00:00",
      "end": "2026-12-18T18:00:00",
      "type": "official",
      "location": "UPOL",
      "description": "Final general de docencia del semestre de invierno.",
      "source": "UPOL"
    },
    {
      "id": "christmas-break",
      "title": "Vacaciones de Navidad",
      "start": "2026-12-19T00:00:00",
      "end": "2027-01-03T23:59:00",
      "type": "official",
      "location": "UPOL",
      "description": "Periodo general sin clases.",
      "source": "UPOL"
    },
    {
      "id": "exchange-exams-end",
      "title": "Fin de exámenes para estudiantes de intercambio",
      "start": "2027-01-31T18:00:00",
      "end": "2027-01-31T18:00:00",
      "type": "official",
      "location": "UPOL",
      "description": "Fecha general de cierre del periodo de exámenes para estudiantes de intercambio.",
      "source": "UPOL"
    }
  ],
  "facultyTravel": [
    {
      "name": "Entre Neředín y Envelopa",
      "fromNeredin": "20–25 min",
      "fromEnvelopa": "20–25 min",
      "mode": "Tranvía 2/7 + paseo",
      "placeName": "Campus Envelopa (residencias Erasmus)"
    },
    {
      "name": "Facultad de Cultura Física y Deporte",
      "fromNeredin": "5–10 min",
      "fromEnvelopa": "25–30 min",
      "mode": "A pie / tranvía 2 o 7",
      "placeName": "Facultad de Cultura Física y Deporte"
    },
    {
      "name": "Facultad de Ciencias",
      "fromNeredin": "20–25 min",
      "fromEnvelopa": "3–6 min",
      "mode": "Tranvía 2/7 + paseo / a pie",
      "placeName": "Facultad de Ciencias (Přírodovědecká fakulta)"
    },
    {
      "name": "Facultad de Derecho",
      "fromNeredin": "20–25 min",
      "fromEnvelopa": "5–8 min",
      "mode": "Tranvía 2/7 + paseo / a pie",
      "placeName": "Facultad de Derecho (Právnická fakulta)"
    },
    {
      "name": "Facultad de Educación",
      "fromNeredin": "22–28 min",
      "fromEnvelopa": "8–12 min",
      "mode": "Tranvía + paseo / a pie",
      "placeName": "Facultad de Educación (Pedagogická fakulta)"
    },
    {
      "name": "Facultad de Filosofía y Letras",
      "fromNeredin": "20–25 min",
      "fromEnvelopa": "10–14 min",
      "mode": "Tranvía + paseo / a pie",
      "placeName": "Facultad de Filosofía y Letras"
    },
    {
      "name": "Facultad de Teología",
      "fromNeredin": "20–25 min",
      "fromEnvelopa": "10–14 min",
      "mode": "Tranvía + paseo / a pie",
      "placeName": "Facultad de Teología Sts. Cirilo y Metodio"
    },
    {
      "name": "Facultad de Medicina",
      "fromNeredin": "15–22 min",
      "fromEnvelopa": "20–28 min",
      "mode": "Tranvía/bus + paseo",
      "placeName": "Facultad de Medicina (Lékařská fakulta)"
    },
    {
      "name": "Facultad de Ciencias de la Salud",
      "fromNeredin": "15–22 min",
      "fromEnvelopa": "20–28 min",
      "mode": "Tranvía/bus + paseo",
      "placeName": "Facultad de Ciencias de la Salud"
    }
  ],
  "levels": [
    {
      "level": 1,
      "name": "Recién llegado",
      "min": 0
    },
    {
      "level": 2,
      "name": "Erasmus curioso",
      "min": 100
    },
    {
      "level": 3,
      "name": "Explorador de Olomouc",
      "min": 300
    },
    {
      "level": 4,
      "name": "Local adoptivo",
      "min": 600
    },
    {
      "level": 5,
      "name": "Moravo honorífico",
      "min": 1000
    },
    {
      "level": 6,
      "name": "Leyenda Erasmus",
      "min": 1500
    }
  ],
  "transport": {
    "ticket": "25 CZK",
    "ticketValidity": "50 min laborables / 70 min fines de semana y festivos en apps",
    "dayTicket": "90 CZK; reducida para estudiantes elegibles: 45 CZK",
    "apps": [
      "DPMO",
      "MobilOK",
      "IDOS",
      "Můj vlak"
    ],
    "note": "Los tiempos son orientativos puerta a puerta. Comprueba la salida exacta en DPMO o IDOS.",
    "officialUrl": "https://www.dpmo.cz/en/"
  },
  "emergency": [
    {
      "label": "Emergencias europeas",
      "number": "112",
      "detail": "Cualquier emergencia"
    },
    {
      "label": "Ambulancia",
      "number": "155",
      "detail": "Urgencia médica"
    },
    {
      "label": "Policía",
      "number": "158",
      "detail": "Seguridad"
    },
    {
      "label": "Bomberos",
      "number": "150",
      "detail": "Incendio y rescate"
    }
  ],
  "residences": {
    "neredin": {
      "name": "Neředín",
      "lat": 49.59449,
      "lng": 17.21605
    },
    "envelopa": {
      "name": "Envelopa",
      "lat": 49.59265,
      "lng": 17.26565
    }
  }
};
